// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v7.34.1
// source: proto/common.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";

export const protobufPackage = "chirp.common";

export enum ErrorCode {
  OK = 0,
  INTERNAL_ERROR = 1,
  INVALID_PARAM = 2,
  AUTH_FAILED = 3,
  SESSION_EXPIRED = 4,
  USER_NOT_FOUND = 5,
  TARGET_OFFLINE = 6,
  /**
   * SERVER_UNAVAILABLE - Server plane: the target service is not connected (or its queue is full),
   * so the request cannot be forwarded right now.
   */
  SERVER_UNAVAILABLE = 7,
  /**
   * RATE_LIMITED - The client exceeded a rate limit (e.g. chat direct-entry login/send
   * windows) and should back off before retrying.
   */
  RATE_LIMITED = 8,
  UNRECOGNIZED = -1,
}

export function errorCodeFromJSON(object: any): ErrorCode {
  switch (object) {
    case 0:
    case "OK":
      return ErrorCode.OK;
    case 1:
    case "INTERNAL_ERROR":
      return ErrorCode.INTERNAL_ERROR;
    case 2:
    case "INVALID_PARAM":
      return ErrorCode.INVALID_PARAM;
    case 3:
    case "AUTH_FAILED":
      return ErrorCode.AUTH_FAILED;
    case 4:
    case "SESSION_EXPIRED":
      return ErrorCode.SESSION_EXPIRED;
    case 5:
    case "USER_NOT_FOUND":
      return ErrorCode.USER_NOT_FOUND;
    case 6:
    case "TARGET_OFFLINE":
      return ErrorCode.TARGET_OFFLINE;
    case 7:
    case "SERVER_UNAVAILABLE":
      return ErrorCode.SERVER_UNAVAILABLE;
    case 8:
    case "RATE_LIMITED":
      return ErrorCode.RATE_LIMITED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ErrorCode.UNRECOGNIZED;
  }
}

export function errorCodeToJSON(object: ErrorCode): string {
  switch (object) {
    case ErrorCode.OK:
      return "OK";
    case ErrorCode.INTERNAL_ERROR:
      return "INTERNAL_ERROR";
    case ErrorCode.INVALID_PARAM:
      return "INVALID_PARAM";
    case ErrorCode.AUTH_FAILED:
      return "AUTH_FAILED";
    case ErrorCode.SESSION_EXPIRED:
      return "SESSION_EXPIRED";
    case ErrorCode.USER_NOT_FOUND:
      return "USER_NOT_FOUND";
    case ErrorCode.TARGET_OFFLINE:
      return "TARGET_OFFLINE";
    case ErrorCode.SERVER_UNAVAILABLE:
      return "SERVER_UNAVAILABLE";
    case ErrorCode.RATE_LIMITED:
      return "RATE_LIMITED";
    case ErrorCode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Empty {
}

function createBaseEmpty(): Empty {
  return {};
}

export const Empty = {
  encode(_: Empty, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Empty {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Empty {
    return {};
  },

  toJSON(_: Empty): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Empty>, I>>(base?: I): Empty {
    return Empty.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Empty>, I>>(_: I): Empty {
    const message = createBaseEmpty();
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };
