// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/chat.proto

package chat

import (
	common "github.com/cui/chirp/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 聊天消息类型
type MsgType int32

const (
	MsgType_TEXT   MsgType = 0  // 文本消息
	MsgType_EMOJI  MsgType = 1  // 表情
	MsgType_VOICE  MsgType = 2  // 语音片段
	MsgType_IMAGE  MsgType = 3  // 图片
	MsgType_SYSTEM MsgType = 99 // 系统消息
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0:  "TEXT",
		1:  "EMOJI",
		2:  "VOICE",
		3:  "IMAGE",
		99: "SYSTEM",
	}
	MsgType_value = map[string]int32{
		"TEXT":   0,
		"EMOJI":  1,
		"VOICE":  2,
		"IMAGE":  3,
		"SYSTEM": 99,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_chat_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_proto_chat_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{0}
}

// 聊天频道类型
type ChannelType int32

const (
	ChannelType_PRIVATE ChannelType = 0 // 私聊 (1v1)
	ChannelType_TEAM    ChannelType = 1 // 队伍频道
	ChannelType_GUILD   ChannelType = 2 // 公会频道
	ChannelType_WORLD   ChannelType = 3 // 世界频道
)

// Enum value maps for ChannelType.
var (
	ChannelType_name = map[int32]string{
		0: "PRIVATE",
		1: "TEAM",
		2: "GUILD",
		3: "WORLD",
	}
	ChannelType_value = map[string]int32{
		"PRIVATE": 0,
		"TEAM":    1,
		"GUILD":   2,
		"WORLD":   3,
	}
)

func (x ChannelType) Enum() *ChannelType {
	p := new(ChannelType)
	*p = x
	return p
}

func (x ChannelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_chat_proto_enumTypes[1].Descriptor()
}

func (ChannelType) Type() protoreflect.EnumType {
	return &file_proto_chat_proto_enumTypes[1]
}

func (x ChannelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelType.Descriptor instead.
func (ChannelType) EnumDescriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{1}
}

// 发送消息请求
type SendMessageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SenderId        string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId      string                 `protobuf:"bytes,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"` // 私聊时的接收者
	ChannelType     ChannelType            `protobuf:"varint,3,opt,name=channel_type,json=channelType,proto3,enum=chirp.chat.ChannelType" json:"channel_type,omitempty"`
	ChannelId       string                 `protobuf:"bytes,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"` // 频道 ID (队伍 ID、公会 ID 等)
	MsgType         MsgType                `protobuf:"varint,5,opt,name=msg_type,json=msgType,proto3,enum=chirp.chat.MsgType" json:"msg_type,omitempty"`
	Content         []byte                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"` // 消息内容 (根据 MsgType 解析)
	ClientTimestamp int64                  `protobuf:"varint,7,opt,name=client_timestamp,json=clientTimestamp,proto3" json:"client_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_proto_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SendMessageRequest) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *SendMessageRequest) GetChannelType() ChannelType {
	if x != nil {
		return x.ChannelType
	}
	return ChannelType_PRIVATE
}

func (x *SendMessageRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *SendMessageRequest) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_TEXT
}

func (x *SendMessageRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SendMessageRequest) GetClientTimestamp() int64 {
	if x != nil {
		return x.ClientTimestamp
	}
	return 0
}

// 发送消息响应
type SendMessageResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Code            common.ErrorCode       `protobuf:"varint,1,opt,name=code,proto3,enum=chirp.common.ErrorCode" json:"code,omitempty"`
	MessageId       string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // 服务器分配的消息 ID
	ServerTimestamp int64                  `protobuf:"varint,3,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_proto_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageResponse) GetCode() common.ErrorCode {
	if x != nil {
		return x.Code
	}
	return common.ErrorCode(0)
}

func (x *SendMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendMessageResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

// 聊天消息
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    string                 `protobuf:"bytes,3,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"` // 私聊时的接收者
	ChannelType   ChannelType            `protobuf:"varint,4,opt,name=channel_type,json=channelType,proto3,enum=chirp.chat.ChannelType" json:"channel_type,omitempty"`
	ChannelId     string                 `protobuf:"bytes,5,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	MsgType       MsgType                `protobuf:"varint,6,opt,name=msg_type,json=msgType,proto3,enum=chirp.chat.MsgType" json:"msg_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ChatMessage) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *ChatMessage) GetChannelType() ChannelType {
	if x != nil {
		return x.ChannelType
	}
	return ChannelType_PRIVATE
}

func (x *ChatMessage) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChatMessage) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_TEXT
}

func (x *ChatMessage) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ChatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 拉取历史消息请求
type GetHistoryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChannelType     ChannelType            `protobuf:"varint,2,opt,name=channel_type,json=channelType,proto3,enum=chirp.chat.ChannelType" json:"channel_type,omitempty"`
	ChannelId       string                 `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	BeforeTimestamp int64                  `protobuf:"varint,4,opt,name=before_timestamp,json=beforeTimestamp,proto3" json:"before_timestamp,omitempty"` // 拉取此时间之前的消息
	Limit           int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`                                            // 最多拉取多少条，默认 50
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_proto_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{3}
}

func (x *GetHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetHistoryRequest) GetChannelType() ChannelType {
	if x != nil {
		return x.ChannelType
	}
	return ChannelType_PRIVATE
}

func (x *GetHistoryRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *GetHistoryRequest) GetBeforeTimestamp() int64 {
	if x != nil {
		return x.BeforeTimestamp
	}
	return 0
}

func (x *GetHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 拉取历史消息响应
type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          common.ErrorCode       `protobuf:"varint,1,opt,name=code,proto3,enum=chirp.common.ErrorCode" json:"code,omitempty"`
	Messages      []*ChatMessage         `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"` // 是否还有更多历史消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_proto_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{4}
}

func (x *GetHistoryResponse) GetCode() common.ErrorCode {
	if x != nil {
		return x.Code
	}
	return common.ErrorCode(0)
}

func (x *GetHistoryResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetHistoryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_proto_chat_proto protoreflect.FileDescriptor

const file_proto_chat_proto_rawDesc = "" +
	"\n" +
	"\x10proto/chat.proto\x12\n" +
	"chirp.chat\x1a\x12proto/common.proto\"\xa2\x02\n" +
	"\x12SendMessageRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\tR\n" +
	"receiverId\x12:\n" +
	"\fchannel_type\x18\x03 \x01(\x0e2\x17.chirp.chat.ChannelTypeR\vchannelType\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x04 \x01(\tR\tchannelId\x12.\n" +
	"\bmsg_type\x18\x05 \x01(\x0e2\x13.chirp.chat.MsgTypeR\amsgType\x12\x18\n" +
	"\acontent\x18\x06 \x01(\fR\acontent\x12)\n" +
	"\x10client_timestamp\x18\a \x01(\x03R\x0fclientTimestamp\"\x8c\x01\n" +
	"\x13SendMessageResponse\x12+\n" +
	"\x04code\x18\x01 \x01(\x0e2\x17.chirp.common.ErrorCodeR\x04code\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12)\n" +
	"\x10server_timestamp\x18\x03 \x01(\x03R\x0fserverTimestamp\"\xad\x02\n" +
	"\vChatMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x03 \x01(\tR\n" +
	"receiverId\x12:\n" +
	"\fchannel_type\x18\x04 \x01(\x0e2\x17.chirp.chat.ChannelTypeR\vchannelType\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x05 \x01(\tR\tchannelId\x12.\n" +
	"\bmsg_type\x18\x06 \x01(\x0e2\x13.chirp.chat.MsgTypeR\amsgType\x12\x18\n" +
	"\acontent\x18\a \x01(\fR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\"\xc8\x01\n" +
	"\x11GetHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12:\n" +
	"\fchannel_type\x18\x02 \x01(\x0e2\x17.chirp.chat.ChannelTypeR\vchannelType\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\tR\tchannelId\x12)\n" +
	"\x10before_timestamp\x18\x04 \x01(\x03R\x0fbeforeTimestamp\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"\x91\x01\n" +
	"\x12GetHistoryResponse\x12+\n" +
	"\x04code\x18\x01 \x01(\x0e2\x17.chirp.common.ErrorCodeR\x04code\x123\n" +
	"\bmessages\x18\x02 \x03(\v2\x17.chirp.chat.ChatMessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore*@\n" +
	"\aMsgType\x12\b\n" +
	"\x04TEXT\x10\x00\x12\t\n" +
	"\x05EMOJI\x10\x01\x12\t\n" +
	"\x05VOICE\x10\x02\x12\t\n" +
	"\x05IMAGE\x10\x03\x12\n" +
	"\n" +
	"\x06SYSTEM\x10c*:\n" +
	"\vChannelType\x12\v\n" +
	"\aPRIVATE\x10\x00\x12\b\n" +
	"\x04TEAM\x10\x01\x12\t\n" +
	"\x05GUILD\x10\x02\x12\t\n" +
	"\x05WORLD\x10\x03B!Z\x1fgithub.com/cui/chirp/proto/chatb\x06proto3"

var (
	file_proto_chat_proto_rawDescOnce sync.Once
	file_proto_chat_proto_rawDescData []byte
)

func file_proto_chat_proto_rawDescGZIP() []byte {
	file_proto_chat_proto_rawDescOnce.Do(func() {
		file_proto_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chat_proto_rawDesc), len(file_proto_chat_proto_rawDesc)))
	})
	return file_proto_chat_proto_rawDescData
}

var file_proto_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_chat_proto_goTypes = []any{
	(MsgType)(0),                // 0: chirp.chat.MsgType
	(ChannelType)(0),            // 1: chirp.chat.ChannelType
	(*SendMessageRequest)(nil),  // 2: chirp.chat.SendMessageRequest
	(*SendMessageResponse)(nil), // 3: chirp.chat.SendMessageResponse
	(*ChatMessage)(nil),         // 4: chirp.chat.ChatMessage
	(*GetHistoryRequest)(nil),   // 5: chirp.chat.GetHistoryRequest
	(*GetHistoryResponse)(nil),  // 6: chirp.chat.GetHistoryResponse
	(common.ErrorCode)(0),       // 7: chirp.common.ErrorCode
}
var file_proto_chat_proto_depIdxs = []int32{
	1, // 0: chirp.chat.SendMessageRequest.channel_type:type_name -> chirp.chat.ChannelType
	0, // 1: chirp.chat.SendMessageRequest.msg_type:type_name -> chirp.chat.MsgType
	7, // 2: chirp.chat.SendMessageResponse.code:type_name -> chirp.common.ErrorCode
	1, // 3: chirp.chat.ChatMessage.channel_type:type_name -> chirp.chat.ChannelType
	0, // 4: chirp.chat.ChatMessage.msg_type:type_name -> chirp.chat.MsgType
	1, // 5: chirp.chat.GetHistoryRequest.channel_type:type_name -> chirp.chat.ChannelType
	7, // 6: chirp.chat.GetHistoryResponse.code:type_name -> chirp.common.ErrorCode
	4, // 7: chirp.chat.GetHistoryResponse.messages:type_name -> chirp.chat.ChatMessage
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_chat_proto_init() }
func file_proto_chat_proto_init() {
	if File_proto_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chat_proto_rawDesc), len(file_proto_chat_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_chat_proto_goTypes,
		DependencyIndexes: file_proto_chat_proto_depIdxs,
		EnumInfos:         file_proto_chat_proto_enumTypes,
		MessageInfos:      file_proto_chat_proto_msgTypes,
	}.Build()
	File_proto_chat_proto = out.File
	file_proto_chat_proto_goTypes = nil
	file_proto_chat_proto_depIdxs = nil
}
