// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/gateway.proto
// Protobuf C++ Version: 6.33.1

#include "proto/gateway.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace chirp {
namespace gateway {

inline constexpr Packet::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        body_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        sequence_{::int64_t{0}},
        msg_id_{static_cast< ::chirp::gateway::MsgID >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR Packet::Packet(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Packet_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PacketDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PacketDefaultTypeInternal() {}
  union {
    Packet _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PacketDefaultTypeInternal _Packet_default_instance_;

inline constexpr HeartbeatPong::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        timestamp_{::int64_t{0}},
        server_time_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR HeartbeatPong::HeartbeatPong(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(HeartbeatPong_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct HeartbeatPongDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HeartbeatPongDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HeartbeatPongDefaultTypeInternal() {}
  union {
    HeartbeatPong _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HeartbeatPongDefaultTypeInternal _HeartbeatPong_default_instance_;

inline constexpr HeartbeatPing::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        timestamp_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR HeartbeatPing::HeartbeatPing(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(HeartbeatPing_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct HeartbeatPingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HeartbeatPingDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HeartbeatPingDefaultTypeInternal() {}
  union {
    HeartbeatPing _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HeartbeatPingDefaultTypeInternal _HeartbeatPing_default_instance_;
}  // namespace gateway
}  // namespace chirp
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_proto_2fgateway_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_proto_2fgateway_2eproto = nullptr;
const ::uint32_t
    TableStruct_proto_2fgateway_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::chirp::gateway::Packet, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::chirp::gateway::Packet, _impl_.msg_id_),
        PROTOBUF_FIELD_OFFSET(::chirp::gateway::Packet, _impl_.sequence_),
        PROTOBUF_FIELD_OFFSET(::chirp::gateway::Packet, _impl_.body_),
        2,
        1,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::chirp::gateway::HeartbeatPing, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::chirp::gateway::HeartbeatPing, _impl_.timestamp_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::chirp::gateway::HeartbeatPong, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::chirp::gateway::HeartbeatPong, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::chirp::gateway::HeartbeatPong, _impl_.server_time_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::chirp::gateway::Packet)},
        {9, sizeof(::chirp::gateway::HeartbeatPing)},
        {14, sizeof(::chirp::gateway::HeartbeatPong)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::chirp::gateway::_Packet_default_instance_._instance,
    &::chirp::gateway::_HeartbeatPing_default_instance_._instance,
    &::chirp::gateway::_HeartbeatPong_default_instance_._instance,
};
const char descriptor_table_protodef_proto_2fgateway_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023proto/gateway.proto\022\rchirp.gateway\032\022pr"
    "oto/common.proto\"N\n\006Packet\022$\n\006msg_id\030\001 \001"
    "(\0162\024.chirp.gateway.MsgID\022\020\n\010sequence\030\002 \001"
    "(\003\022\014\n\004body\030\003 \001(\014\"\"\n\rHeartbeatPing\022\021\n\ttim"
    "estamp\030\001 \001(\003\"7\n\rHeartbeatPong\022\021\n\ttimesta"
    "mp\030\001 \001(\003\022\023\n\013server_time\030\002 \001(\003*q\n\005MsgID\022\013"
    "\n\007UNKNOWN\020\000\022\023\n\016HEARTBEAT_PING\020\351\007\022\023\n\016HEAR"
    "TBEAT_PONG\020\352\007\022\016\n\tLOGIN_REQ\020\353\007\022\017\n\nLOGIN_R"
    "ESP\020\354\007\022\020\n\013KICK_NOTIFY\020\355\007B$Z\"github.com/c"
    "ui/chirp/proto/gatewayb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_proto_2fgateway_2eproto_deps[1] = {
        &::descriptor_table_proto_2fcommon_2eproto,
};
static ::absl::once_flag descriptor_table_proto_2fgateway_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_proto_2fgateway_2eproto = {
    false,
    false,
    390,
    descriptor_table_protodef_proto_2fgateway_2eproto,
    "proto/gateway.proto",
    &descriptor_table_proto_2fgateway_2eproto_once,
    descriptor_table_proto_2fgateway_2eproto_deps,
    1,
    3,
    schemas,
    file_default_instances,
    TableStruct_proto_2fgateway_2eproto::offsets,
    file_level_enum_descriptors_proto_2fgateway_2eproto,
    file_level_service_descriptors_proto_2fgateway_2eproto,
};
namespace chirp {
namespace gateway {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL MsgID_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_proto_2fgateway_2eproto);
  return file_level_enum_descriptors_proto_2fgateway_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t MsgID_internal_data_[] = {
    65536u, 327680u, 1004u, 1002u, 1005u, 1001u, 1003u, };
// ===================================================================

class Packet::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Packet>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Packet, _impl_._has_bits_);
};

Packet::Packet(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Packet_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:chirp.gateway.Packet)
}
PROTOBUF_NDEBUG_INLINE Packet::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::chirp::gateway::Packet& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        body_(arena, from.body_) {}

Packet::Packet(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Packet& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Packet_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Packet* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, sequence_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, sequence_),
           offsetof(Impl_, msg_id_) -
               offsetof(Impl_, sequence_) +
               sizeof(Impl_::msg_id_));

  // @@protoc_insertion_point(copy_constructor:chirp.gateway.Packet)
}
PROTOBUF_NDEBUG_INLINE Packet::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        body_(arena) {}

inline void Packet::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, sequence_),
           0,
           offsetof(Impl_, msg_id_) -
               offsetof(Impl_, sequence_) +
               sizeof(Impl_::msg_id_));
}
Packet::~Packet() {
  // @@protoc_insertion_point(destructor:chirp.gateway.Packet)
  SharedDtor(*this);
}
inline void Packet::SharedDtor(MessageLite& self) {
  Packet& this_ = static_cast<Packet&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.body_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Packet::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Packet(arena);
}
constexpr auto Packet::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Packet),
                                            alignof(Packet));
}
constexpr auto Packet::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Packet_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Packet::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Packet>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Packet::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Packet>(), &Packet::ByteSizeLong,
              &Packet::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Packet, _impl_._cached_size_),
          false,
      },
      &Packet::kDescriptorMethods,
      &descriptor_table_proto_2fgateway_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Packet_class_data_ =
        Packet::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Packet::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Packet_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Packet_class_data_.tc_table);
  return Packet_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
Packet::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Packet, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Packet_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::chirp::gateway::Packet>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .chirp.gateway.MsgID msg_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Packet, _impl_.msg_id_), 2>(),
     {8, 2, 0,
      PROTOBUF_FIELD_OFFSET(Packet, _impl_.msg_id_)}},
    // int64 sequence = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Packet, _impl_.sequence_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(Packet, _impl_.sequence_)}},
    // bytes body = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 0, 0,
      PROTOBUF_FIELD_OFFSET(Packet, _impl_.body_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .chirp.gateway.MsgID msg_id = 1;
    {PROTOBUF_FIELD_OFFSET(Packet, _impl_.msg_id_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // int64 sequence = 2;
    {PROTOBUF_FIELD_OFFSET(Packet, _impl_.sequence_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // bytes body = 3;
    {PROTOBUF_FIELD_OFFSET(Packet, _impl_.body_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Packet::Clear() {
// @@protoc_insertion_point(message_clear_start:chirp.gateway.Packet)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.body_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000006U)) {
    ::memset(&_impl_.sequence_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.msg_id_) -
        reinterpret_cast<char*>(&_impl_.sequence_)) + sizeof(_impl_.msg_id_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Packet::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Packet& this_ = static_cast<const Packet&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Packet::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Packet& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:chirp.gateway.Packet)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .chirp.gateway.MsgID msg_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_msg_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_msg_id(), target);
    }
  }

  // int64 sequence = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_sequence() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
              stream, this_._internal_sequence(), target);
    }
  }

  // bytes body = 3;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_body().empty()) {
      const ::std::string& _s = this_._internal_body();
      target = stream->WriteBytesMaybeAliased(3, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:chirp.gateway.Packet)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Packet::ByteSizeLong(const MessageLite& base) {
  const Packet& this_ = static_cast<const Packet&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Packet::ByteSizeLong() const {
  const Packet& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:chirp.gateway.Packet)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // bytes body = 3;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_body().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_body());
      }
    }
    // int64 sequence = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_sequence() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_sequence());
      }
    }
    // .chirp.gateway.MsgID msg_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_msg_id() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_msg_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Packet::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Packet*>(&to_msg);
  auto& from = static_cast<const Packet&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:chirp.gateway.Packet)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_body().empty()) {
        _this->_internal_set_body(from._internal_body());
      } else {
        if (_this->_impl_.body_.IsDefault()) {
          _this->_internal_set_body("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_sequence() != 0) {
        _this->_impl_.sequence_ = from._impl_.sequence_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_msg_id() != 0) {
        _this->_impl_.msg_id_ = from._impl_.msg_id_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Packet::CopyFrom(const Packet& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:chirp.gateway.Packet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Packet::InternalSwap(Packet* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.body_, &other->_impl_.body_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Packet, _impl_.msg_id_)
      + sizeof(Packet::_impl_.msg_id_)
      - PROTOBUF_FIELD_OFFSET(Packet, _impl_.sequence_)>(
          reinterpret_cast<char*>(&_impl_.sequence_),
          reinterpret_cast<char*>(&other->_impl_.sequence_));
}

::google::protobuf::Metadata Packet::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class HeartbeatPing::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<HeartbeatPing>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(HeartbeatPing, _impl_._has_bits_);
};

HeartbeatPing::HeartbeatPing(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, HeartbeatPing_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:chirp.gateway.HeartbeatPing)
}
HeartbeatPing::HeartbeatPing(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const HeartbeatPing& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, HeartbeatPing_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE HeartbeatPing::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void HeartbeatPing::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.timestamp_ = {};
}
HeartbeatPing::~HeartbeatPing() {
  // @@protoc_insertion_point(destructor:chirp.gateway.HeartbeatPing)
  SharedDtor(*this);
}
inline void HeartbeatPing::SharedDtor(MessageLite& self) {
  HeartbeatPing& this_ = static_cast<HeartbeatPing&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL HeartbeatPing::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) HeartbeatPing(arena);
}
constexpr auto HeartbeatPing::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(HeartbeatPing),
                                            alignof(HeartbeatPing));
}
constexpr auto HeartbeatPing::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_HeartbeatPing_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &HeartbeatPing::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<HeartbeatPing>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &HeartbeatPing::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<HeartbeatPing>(), &HeartbeatPing::ByteSizeLong,
              &HeartbeatPing::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(HeartbeatPing, _impl_._cached_size_),
          false,
      },
      &HeartbeatPing::kDescriptorMethods,
      &descriptor_table_proto_2fgateway_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull HeartbeatPing_class_data_ =
        HeartbeatPing::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
HeartbeatPing::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&HeartbeatPing_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(HeartbeatPing_class_data_.tc_table);
  return HeartbeatPing_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
HeartbeatPing::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(HeartbeatPing, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    HeartbeatPing_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::chirp::gateway::HeartbeatPing>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 timestamp = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(HeartbeatPing, _impl_.timestamp_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(HeartbeatPing, _impl_.timestamp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 timestamp = 1;
    {PROTOBUF_FIELD_OFFSET(HeartbeatPing, _impl_.timestamp_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void HeartbeatPing::Clear() {
// @@protoc_insertion_point(message_clear_start:chirp.gateway.HeartbeatPing)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.timestamp_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL HeartbeatPing::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const HeartbeatPing& this_ = static_cast<const HeartbeatPing&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL HeartbeatPing::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const HeartbeatPing& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:chirp.gateway.HeartbeatPing)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int64 timestamp = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_timestamp() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
              stream, this_._internal_timestamp(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:chirp.gateway.HeartbeatPing)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t HeartbeatPing::ByteSizeLong(const MessageLite& base) {
  const HeartbeatPing& this_ = static_cast<const HeartbeatPing&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t HeartbeatPing::ByteSizeLong() const {
  const HeartbeatPing& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:chirp.gateway.HeartbeatPing)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int64 timestamp = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_timestamp() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_timestamp());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void HeartbeatPing::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<HeartbeatPing*>(&to_msg);
  auto& from = static_cast<const HeartbeatPing&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:chirp.gateway.HeartbeatPing)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (from._internal_timestamp() != 0) {
      _this->_impl_.timestamp_ = from._impl_.timestamp_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void HeartbeatPing::CopyFrom(const HeartbeatPing& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:chirp.gateway.HeartbeatPing)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void HeartbeatPing::InternalSwap(HeartbeatPing* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.timestamp_, other->_impl_.timestamp_);
}

::google::protobuf::Metadata HeartbeatPing::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class HeartbeatPong::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<HeartbeatPong>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(HeartbeatPong, _impl_._has_bits_);
};

HeartbeatPong::HeartbeatPong(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, HeartbeatPong_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:chirp.gateway.HeartbeatPong)
}
HeartbeatPong::HeartbeatPong(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const HeartbeatPong& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, HeartbeatPong_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE HeartbeatPong::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void HeartbeatPong::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, timestamp_),
           0,
           offsetof(Impl_, server_time_) -
               offsetof(Impl_, timestamp_) +
               sizeof(Impl_::server_time_));
}
HeartbeatPong::~HeartbeatPong() {
  // @@protoc_insertion_point(destructor:chirp.gateway.HeartbeatPong)
  SharedDtor(*this);
}
inline void HeartbeatPong::SharedDtor(MessageLite& self) {
  HeartbeatPong& this_ = static_cast<HeartbeatPong&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL HeartbeatPong::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) HeartbeatPong(arena);
}
constexpr auto HeartbeatPong::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(HeartbeatPong),
                                            alignof(HeartbeatPong));
}
constexpr auto HeartbeatPong::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_HeartbeatPong_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &HeartbeatPong::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<HeartbeatPong>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &HeartbeatPong::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<HeartbeatPong>(), &HeartbeatPong::ByteSizeLong,
              &HeartbeatPong::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(HeartbeatPong, _impl_._cached_size_),
          false,
      },
      &HeartbeatPong::kDescriptorMethods,
      &descriptor_table_proto_2fgateway_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull HeartbeatPong_class_data_ =
        HeartbeatPong::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
HeartbeatPong::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&HeartbeatPong_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(HeartbeatPong_class_data_.tc_table);
  return HeartbeatPong_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
HeartbeatPong::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(HeartbeatPong, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    HeartbeatPong_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::chirp::gateway::HeartbeatPong>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 server_time = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(HeartbeatPong, _impl_.server_time_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(HeartbeatPong, _impl_.server_time_)}},
    // int64 timestamp = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(HeartbeatPong, _impl_.timestamp_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(HeartbeatPong, _impl_.timestamp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 timestamp = 1;
    {PROTOBUF_FIELD_OFFSET(HeartbeatPong, _impl_.timestamp_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // int64 server_time = 2;
    {PROTOBUF_FIELD_OFFSET(HeartbeatPong, _impl_.server_time_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void HeartbeatPong::Clear() {
// @@protoc_insertion_point(message_clear_start:chirp.gateway.HeartbeatPong)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    ::memset(&_impl_.timestamp_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.server_time_) -
        reinterpret_cast<char*>(&_impl_.timestamp_)) + sizeof(_impl_.server_time_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL HeartbeatPong::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const HeartbeatPong& this_ = static_cast<const HeartbeatPong&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL HeartbeatPong::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const HeartbeatPong& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:chirp.gateway.HeartbeatPong)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int64 timestamp = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_timestamp() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
              stream, this_._internal_timestamp(), target);
    }
  }

  // int64 server_time = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_server_time() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
              stream, this_._internal_server_time(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:chirp.gateway.HeartbeatPong)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t HeartbeatPong::ByteSizeLong(const MessageLite& base) {
  const HeartbeatPong& this_ = static_cast<const HeartbeatPong&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t HeartbeatPong::ByteSizeLong() const {
  const HeartbeatPong& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:chirp.gateway.HeartbeatPong)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // int64 timestamp = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_timestamp() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_timestamp());
      }
    }
    // int64 server_time = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_server_time() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_server_time());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void HeartbeatPong::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<HeartbeatPong*>(&to_msg);
  auto& from = static_cast<const HeartbeatPong&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:chirp.gateway.HeartbeatPong)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_timestamp() != 0) {
        _this->_impl_.timestamp_ = from._impl_.timestamp_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_server_time() != 0) {
        _this->_impl_.server_time_ = from._impl_.server_time_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void HeartbeatPong::CopyFrom(const HeartbeatPong& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:chirp.gateway.HeartbeatPong)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void HeartbeatPong::InternalSwap(HeartbeatPong* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(HeartbeatPong, _impl_.server_time_)
      + sizeof(HeartbeatPong::_impl_.server_time_)
      - PROTOBUF_FIELD_OFFSET(HeartbeatPong, _impl_.timestamp_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_));
}

::google::protobuf::Metadata HeartbeatPong::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace gateway
}  // namespace chirp
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_proto_2fgateway_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
