// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: proto/gateway.proto

package gateway

import (
	chat "github.com/cui/chirp/proto/go/chat"
	common "github.com/cui/chirp/proto/go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message ID definition for dispatching
type MsgID int32

const (
	MsgID_UNKNOWN        MsgID = 0
	MsgID_HEARTBEAT_PING MsgID = 1001
	MsgID_HEARTBEAT_PONG MsgID = 1002
	MsgID_LOGIN_REQ      MsgID = 1003
	MsgID_LOGIN_RESP     MsgID = 1004
	MsgID_KICK_NOTIFY    MsgID = 1005
	MsgID_LOGOUT_REQ     MsgID = 1006
	MsgID_LOGOUT_RESP    MsgID = 1007
	// Enhanced auth messages
	MsgID_REGISTER_REQ         MsgID = 1008
	MsgID_REGISTER_RESP        MsgID = 1009
	MsgID_PASSWORD_LOGIN_REQ   MsgID = 1010
	MsgID_PASSWORD_LOGIN_RESP  MsgID = 1011
	MsgID_REFRESH_TOKEN_REQ    MsgID = 1012
	MsgID_REFRESH_TOKEN_RESP   MsgID = 1013
	MsgID_GET_SESSIONS_REQ     MsgID = 1014
	MsgID_GET_SESSIONS_RESP    MsgID = 1015
	MsgID_REVOKE_SESSION_REQ   MsgID = 1016
	MsgID_REVOKE_SESSION_RESP  MsgID = 1017
	MsgID_CHANGE_PASSWORD_REQ  MsgID = 1018
	MsgID_CHANGE_PASSWORD_RESP MsgID = 1019
	// Chat service. Both gateways relay these verbatim through the per-client
	// ChatBridge pipeline (gateway and app_gateway, each with --chat_host);
	// chat answers on the same internal connection, so no edge synthesizes
	// these responses.
	MsgID_SEND_MESSAGE_REQ    MsgID = 2001
	MsgID_SEND_MESSAGE_RESP   MsgID = 2002
	MsgID_GET_HISTORY_REQ     MsgID = 2003
	MsgID_GET_HISTORY_RESP    MsgID = 2004
	MsgID_CHAT_MESSAGE_NOTIFY MsgID = 2005
	// Group chat
	MsgID_CREATE_GROUP_REQ           MsgID = 2101
	MsgID_CREATE_GROUP_RESP          MsgID = 2102
	MsgID_JOIN_GROUP_REQ             MsgID = 2103
	MsgID_JOIN_GROUP_RESP            MsgID = 2104
	MsgID_LEAVE_GROUP_REQ            MsgID = 2105
	MsgID_LEAVE_GROUP_RESP           MsgID = 2106
	MsgID_KICK_MEMBER_REQ            MsgID = 2107
	MsgID_KICK_MEMBER_RESP           MsgID = 2108
	MsgID_GET_GROUP_INFO_REQ         MsgID = 2109
	MsgID_GET_GROUP_INFO_RESP        MsgID = 2110
	MsgID_GET_GROUP_MEMBERS_REQ      MsgID = 2111
	MsgID_GET_GROUP_MEMBERS_RESP     MsgID = 2112
	MsgID_GET_USER_GROUPS_REQ        MsgID = 2113
	MsgID_GET_USER_GROUPS_RESP       MsgID = 2114
	MsgID_INVITE_TO_GROUP_REQ        MsgID = 2115
	MsgID_INVITE_TO_GROUP_RESP       MsgID = 2116
	MsgID_GROUP_CREATED_NOTIFY       MsgID = 2117
	MsgID_GROUP_MEMBER_JOINED_NOTIFY MsgID = 2118
	MsgID_GROUP_MEMBER_LEFT_NOTIFY   MsgID = 2119
	MsgID_GROUP_MEMBER_KICKED_NOTIFY MsgID = 2120
	MsgID_GROUP_UPDATED_NOTIFY       MsgID = 2121
	// Read receipts
	MsgID_MARK_READ_REQ          MsgID = 2201
	MsgID_MARK_READ_RESP         MsgID = 2202
	MsgID_GET_READ_RECEIPTS_REQ  MsgID = 2203
	MsgID_GET_READ_RECEIPTS_RESP MsgID = 2204
	MsgID_GET_UNREAD_COUNT_REQ   MsgID = 2205
	MsgID_GET_UNREAD_COUNT_RESP  MsgID = 2206
	MsgID_MESSAGE_READ_NOTIFY    MsgID = 2207
	// Typing indicators
	MsgID_TYPING_INDICATOR_NOTIFY MsgID = 2208
	// Message delivery tracking
	MsgID_MESSAGE_ACK        MsgID = 2209
	MsgID_MESSAGE_NACK       MsgID = 2210
	MsgID_TRACK_MESSAGE_REQ  MsgID = 2211
	MsgID_TRACK_MESSAGE_RESP MsgID = 2212
	// Enhanced history
	MsgID_GET_HISTORY_V2_REQ  MsgID = 2213
	MsgID_GET_HISTORY_V2_RESP MsgID = 2214
	// Message reactions
	MsgID_ADD_REACTION_REQ        MsgID = 2215
	MsgID_ADD_REACTION_RESP       MsgID = 2216
	MsgID_REMOVE_REACTION_REQ     MsgID = 2217
	MsgID_REMOVE_REACTION_RESP    MsgID = 2218
	MsgID_GET_REACTIONS_REQ       MsgID = 2219
	MsgID_GET_REACTIONS_RESP      MsgID = 2220
	MsgID_REACTION_ADDED_NOTIFY   MsgID = 2221
	MsgID_REACTION_REMOVED_NOTIFY MsgID = 2222
	// Typing queries
	MsgID_GET_TYPING_USERS_REQ  MsgID = 2223
	MsgID_GET_TYPING_USERS_RESP MsgID = 2224
	// Message edit/delete
	MsgID_EDIT_MESSAGE_REQ       MsgID = 2225
	MsgID_EDIT_MESSAGE_RESP      MsgID = 2226
	MsgID_DELETE_MESSAGE_REQ     MsgID = 2227
	MsgID_DELETE_MESSAGE_RESP    MsgID = 2228
	MsgID_BULK_DELETE_REQ        MsgID = 2229
	MsgID_BULK_DELETE_RESP       MsgID = 2230
	MsgID_MESSAGE_EDITED_NOTIFY  MsgID = 2231
	MsgID_MESSAGE_DELETED_NOTIFY MsgID = 2232
	// Mentions
	MsgID_GET_MENTION_SUGGESTIONS_REQ  MsgID = 2233
	MsgID_GET_MENTION_SUGGESTIONS_RESP MsgID = 2234
	// Channel mute (player-level push filter; history stays browsable)
	MsgID_SET_CHANNEL_MUTE_REQ   MsgID = 2235
	MsgID_SET_CHANNEL_MUTE_RESP  MsgID = 2236
	MsgID_GET_CHANNEL_MUTES_REQ  MsgID = 2237
	MsgID_GET_CHANNEL_MUTES_RESP MsgID = 2238
	// Social service
	MsgID_ADD_FRIEND_REQ             MsgID = 3001
	MsgID_ADD_FRIEND_RESP            MsgID = 3002
	MsgID_FRIEND_REQUEST_ACTION_REQ  MsgID = 3003
	MsgID_FRIEND_REQUEST_ACTION_RESP MsgID = 3004
	MsgID_REMOVE_FRIEND_REQ          MsgID = 3005
	MsgID_REMOVE_FRIEND_RESP         MsgID = 3006
	MsgID_GET_FRIEND_LIST_REQ        MsgID = 3007
	MsgID_GET_FRIEND_LIST_RESP       MsgID = 3008
	MsgID_GET_PENDING_REQUESTS_REQ   MsgID = 3009
	MsgID_GET_PENDING_REQUESTS_RESP  MsgID = 3010
	MsgID_BLOCK_USER_REQ             MsgID = 3011
	MsgID_BLOCK_USER_RESP            MsgID = 3012
	MsgID_UNBLOCK_USER_REQ           MsgID = 3013
	MsgID_UNBLOCK_USER_RESP          MsgID = 3014
	MsgID_GET_BLOCKED_LIST_REQ       MsgID = 3015
	MsgID_GET_BLOCKED_LIST_RESP      MsgID = 3016
	MsgID_SET_PRESENCE_REQ           MsgID = 3017
	MsgID_SET_PRESENCE_RESP          MsgID = 3018
	MsgID_GET_PRESENCE_REQ           MsgID = 3019
	MsgID_GET_PRESENCE_RESP          MsgID = 3020
	MsgID_PRESENCE_NOTIFY            MsgID = 3021
	MsgID_FRIEND_REQUEST_NOTIFY      MsgID = 3022
	MsgID_FRIEND_ACCEPTED_NOTIFY     MsgID = 3023
	MsgID_FRIEND_REMOVED_NOTIFY      MsgID = 3024
	// Voice service
	MsgID_CREATE_ROOM_REQ                  MsgID = 4001
	MsgID_CREATE_ROOM_RESP                 MsgID = 4002
	MsgID_JOIN_ROOM_REQ                    MsgID = 4003
	MsgID_JOIN_ROOM_RESP                   MsgID = 4004
	MsgID_LEAVE_ROOM_REQ                   MsgID = 4005
	MsgID_LEAVE_ROOM_RESP                  MsgID = 4006
	MsgID_ICE_CANDIDATE_MSG                MsgID = 4007
	MsgID_SDP_OFFER_MSG                    MsgID = 4008
	MsgID_SDP_ANSWER_MSG                   MsgID = 4009
	MsgID_GET_ROOM_INFO_REQ                MsgID = 4010
	MsgID_GET_ROOM_INFO_RESP               MsgID = 4011
	MsgID_GET_USER_ROOM_REQ                MsgID = 4012
	MsgID_GET_USER_ROOM_RESP               MsgID = 4013
	MsgID_SET_MUTE_REQ                     MsgID = 4014
	MsgID_SET_MUTE_RESP                    MsgID = 4015
	MsgID_SET_DEAFEN_REQ                   MsgID = 4016
	MsgID_SET_DEAFEN_RESP                  MsgID = 4017
	MsgID_PARTICIPANT_JOINED_NOTIFY        MsgID = 4018
	MsgID_PARTICIPANT_LEFT_NOTIFY          MsgID = 4019
	MsgID_PARTICIPANT_STATE_CHANGED_NOTIFY MsgID = 4020
	MsgID_SPEAKING_NOTIFY                  MsgID = 4021
	// Server plane: game backend <-> chirp (authenticated services, not users).
	// See proto/game_server_gateway.proto for the payloads.
	MsgID_SERVER_AUTH_REQ             MsgID = 5001
	MsgID_SERVER_AUTH_RESP            MsgID = 5002
	MsgID_SERVER_HEARTBEAT_PING       MsgID = 5003
	MsgID_SERVER_HEARTBEAT_PONG       MsgID = 5004
	MsgID_INJECT_MESSAGE_REQ          MsgID = 5005
	MsgID_INJECT_MESSAGE_RESP         MsgID = 5006
	MsgID_INJECT_MESSAGE_NOTIFY       MsgID = 5007
	MsgID_EVENT_PUBLISH_REQ           MsgID = 5008
	MsgID_EVENT_PUBLISH_RESP          MsgID = 5009
	MsgID_EVENT_DELIVER_NOTIFY        MsgID = 5010
	MsgID_EVENT_ACK_REQ               MsgID = 5011
	MsgID_EVENT_ACK_RESP              MsgID = 5012
	MsgID_BIND_PLAYER_IDENTITY_REQ    MsgID = 5013
	MsgID_BIND_PLAYER_IDENTITY_RESP   MsgID = 5014
	MsgID_UNBIND_PLAYER_IDENTITY_REQ  MsgID = 5015
	MsgID_UNBIND_PLAYER_IDENTITY_RESP MsgID = 5016
	MsgID_GET_PLAYER_IDENTITIES_REQ   MsgID = 5017
	MsgID_GET_PLAYER_IDENTITIES_RESP  MsgID = 5018
	MsgID_RESOLVE_GAME_USER_REQ       MsgID = 5019
	MsgID_RESOLVE_GAME_USER_RESP      MsgID = 5020
	// Player channel subscriptions: asserted by game backends on this plane,
	// and forwarded by app_gateway for self-served players (player_id pinned
	// to the authenticated user). See proto/game_server_gateway.proto.
	MsgID_SUBSCRIBE_PLAYER_CHANNEL_REQ    MsgID = 5021
	MsgID_SUBSCRIBE_PLAYER_CHANNEL_RESP   MsgID = 5022
	MsgID_UNSUBSCRIBE_PLAYER_CHANNEL_REQ  MsgID = 5023
	MsgID_UNSUBSCRIBE_PLAYER_CHANNEL_RESP MsgID = 5024
	MsgID_GET_PLAYER_SUBSCRIPTIONS_REQ    MsgID = 5025
	MsgID_GET_PLAYER_SUBSCRIPTIONS_RESP   MsgID = 5026
	// Unified unread (WP-8 slice 4): the hub's fan-in badge ledger, backed by
	// the fan-out copies injected with a game_id. Independent of the chat
	// read cursors (2201-2207); app_gateway forwards these for self-served
	// players (player_id pinned to the authenticated user). Bodies are
	// chirp.game_server_gateway.* messages; see proto/game_server_gateway.proto.
	MsgID_MARK_CHANNELS_READ_REQ  MsgID = 5027
	MsgID_MARK_CHANNELS_READ_RESP MsgID = 5028
	MsgID_GET_UNREAD_SUMMARY_REQ  MsgID = 5029
	MsgID_GET_UNREAD_SUMMARY_RESP MsgID = 5030
	// Chat peer registration: game_chat (spoke) registers with app_chat (hub)
	// so channel messages bridge between the two planes natively - no external
	// bridge process. See docs/architecture.md (对等注册协议).
	MsgID_PEER_REGISTER_REQ          MsgID = 5050
	MsgID_PEER_REGISTER_RESP         MsgID = 5051
	MsgID_CHANNEL_MESSAGE_NOTIFY     MsgID = 5052
	MsgID_PEER_INJECT_MESSAGE_NOTIFY MsgID = 5053
	// Notification plane: device registration forwarded by app_gateway and
	// push requests from internal services (chat). Bodies are
	// chirp.app_notification.* messages; see proto/app_notification.proto.
	MsgID_REGISTER_DEVICE_REQ      MsgID = 6001
	MsgID_REGISTER_DEVICE_RESP     MsgID = 6002
	MsgID_UNREGISTER_DEVICE_REQ    MsgID = 6003
	MsgID_UNREGISTER_DEVICE_RESP   MsgID = 6004
	MsgID_UPDATE_DEVICE_TOKEN_REQ  MsgID = 6005
	MsgID_UPDATE_DEVICE_TOKEN_RESP MsgID = 6006
	MsgID_GET_USER_DEVICES_REQ     MsgID = 6007
	MsgID_GET_USER_DEVICES_RESP    MsgID = 6008
	MsgID_PUSH_NOTIFICATION_REQ    MsgID = 6009
	MsgID_PUSH_NOTIFICATION_RESP   MsgID = 6010
	// Party plane: cross-game team-up on the player plane (membership and
	// signaling identity are the player, decoupled from the game-scoped voice
	// rooms; see docs/architecture.md). Invite-accept only — no join codes.
	// Bodies are chirp.party.* messages; see proto/party.proto.
	MsgID_CREATE_PARTY_REQ           MsgID = 7001
	MsgID_CREATE_PARTY_RESP          MsgID = 7002
	MsgID_DISBAND_PARTY_REQ          MsgID = 7003
	MsgID_DISBAND_PARTY_RESP         MsgID = 7004
	MsgID_INVITE_TO_PARTY_REQ        MsgID = 7005
	MsgID_INVITE_TO_PARTY_RESP       MsgID = 7006
	MsgID_INVITE_NOTIFY              MsgID = 7007 // to the invitee, all their devices
	MsgID_ACCEPT_INVITE_REQ          MsgID = 7008
	MsgID_ACCEPT_INVITE_RESP         MsgID = 7009
	MsgID_DECLINE_INVITE_REQ         MsgID = 7010
	MsgID_DECLINE_INVITE_RESP        MsgID = 7011
	MsgID_INVITE_RESULT_NOTIFY       MsgID = 7012 // to the inviter (accept/decline)
	MsgID_LEAVE_PARTY_REQ            MsgID = 7013
	MsgID_LEAVE_PARTY_RESP           MsgID = 7014
	MsgID_KICK_PARTY_MEMBER_REQ      MsgID = 7015
	MsgID_KICK_PARTY_MEMBER_RESP     MsgID = 7016
	MsgID_TRANSFER_LEADER_REQ        MsgID = 7017
	MsgID_TRANSFER_LEADER_RESP       MsgID = 7018
	MsgID_SET_READY_REQ              MsgID = 7019
	MsgID_SET_READY_RESP             MsgID = 7020
	MsgID_PARTY_JOINED_NOTIFY        MsgID = 7021 // everyone except the joiner
	MsgID_PARTY_LEFT_NOTIFY          MsgID = 7022 // everyone except the leaver
	MsgID_PARTY_KICKED_NOTIFY        MsgID = 7023 // the kicked user only
	MsgID_PARTY_STATE_CHANGED_NOTIFY MsgID = 7024 // full PartyInfo snapshot, ALL members
	MsgID_PARTY_DISBANDED_NOTIFY     MsgID = 7025 // remaining members on disband
	MsgID_GET_MY_PARTY_REQ           MsgID = 7026
	MsgID_GET_MY_PARTY_RESP          MsgID = 7027
)

// Enum value maps for MsgID.
var (
	MsgID_name = map[int32]string{
		0:    "UNKNOWN",
		1001: "HEARTBEAT_PING",
		1002: "HEARTBEAT_PONG",
		1003: "LOGIN_REQ",
		1004: "LOGIN_RESP",
		1005: "KICK_NOTIFY",
		1006: "LOGOUT_REQ",
		1007: "LOGOUT_RESP",
		1008: "REGISTER_REQ",
		1009: "REGISTER_RESP",
		1010: "PASSWORD_LOGIN_REQ",
		1011: "PASSWORD_LOGIN_RESP",
		1012: "REFRESH_TOKEN_REQ",
		1013: "REFRESH_TOKEN_RESP",
		1014: "GET_SESSIONS_REQ",
		1015: "GET_SESSIONS_RESP",
		1016: "REVOKE_SESSION_REQ",
		1017: "REVOKE_SESSION_RESP",
		1018: "CHANGE_PASSWORD_REQ",
		1019: "CHANGE_PASSWORD_RESP",
		2001: "SEND_MESSAGE_REQ",
		2002: "SEND_MESSAGE_RESP",
		2003: "GET_HISTORY_REQ",
		2004: "GET_HISTORY_RESP",
		2005: "CHAT_MESSAGE_NOTIFY",
		2101: "CREATE_GROUP_REQ",
		2102: "CREATE_GROUP_RESP",
		2103: "JOIN_GROUP_REQ",
		2104: "JOIN_GROUP_RESP",
		2105: "LEAVE_GROUP_REQ",
		2106: "LEAVE_GROUP_RESP",
		2107: "KICK_MEMBER_REQ",
		2108: "KICK_MEMBER_RESP",
		2109: "GET_GROUP_INFO_REQ",
		2110: "GET_GROUP_INFO_RESP",
		2111: "GET_GROUP_MEMBERS_REQ",
		2112: "GET_GROUP_MEMBERS_RESP",
		2113: "GET_USER_GROUPS_REQ",
		2114: "GET_USER_GROUPS_RESP",
		2115: "INVITE_TO_GROUP_REQ",
		2116: "INVITE_TO_GROUP_RESP",
		2117: "GROUP_CREATED_NOTIFY",
		2118: "GROUP_MEMBER_JOINED_NOTIFY",
		2119: "GROUP_MEMBER_LEFT_NOTIFY",
		2120: "GROUP_MEMBER_KICKED_NOTIFY",
		2121: "GROUP_UPDATED_NOTIFY",
		2201: "MARK_READ_REQ",
		2202: "MARK_READ_RESP",
		2203: "GET_READ_RECEIPTS_REQ",
		2204: "GET_READ_RECEIPTS_RESP",
		2205: "GET_UNREAD_COUNT_REQ",
		2206: "GET_UNREAD_COUNT_RESP",
		2207: "MESSAGE_READ_NOTIFY",
		2208: "TYPING_INDICATOR_NOTIFY",
		2209: "MESSAGE_ACK",
		2210: "MESSAGE_NACK",
		2211: "TRACK_MESSAGE_REQ",
		2212: "TRACK_MESSAGE_RESP",
		2213: "GET_HISTORY_V2_REQ",
		2214: "GET_HISTORY_V2_RESP",
		2215: "ADD_REACTION_REQ",
		2216: "ADD_REACTION_RESP",
		2217: "REMOVE_REACTION_REQ",
		2218: "REMOVE_REACTION_RESP",
		2219: "GET_REACTIONS_REQ",
		2220: "GET_REACTIONS_RESP",
		2221: "REACTION_ADDED_NOTIFY",
		2222: "REACTION_REMOVED_NOTIFY",
		2223: "GET_TYPING_USERS_REQ",
		2224: "GET_TYPING_USERS_RESP",
		2225: "EDIT_MESSAGE_REQ",
		2226: "EDIT_MESSAGE_RESP",
		2227: "DELETE_MESSAGE_REQ",
		2228: "DELETE_MESSAGE_RESP",
		2229: "BULK_DELETE_REQ",
		2230: "BULK_DELETE_RESP",
		2231: "MESSAGE_EDITED_NOTIFY",
		2232: "MESSAGE_DELETED_NOTIFY",
		2233: "GET_MENTION_SUGGESTIONS_REQ",
		2234: "GET_MENTION_SUGGESTIONS_RESP",
		2235: "SET_CHANNEL_MUTE_REQ",
		2236: "SET_CHANNEL_MUTE_RESP",
		2237: "GET_CHANNEL_MUTES_REQ",
		2238: "GET_CHANNEL_MUTES_RESP",
		3001: "ADD_FRIEND_REQ",
		3002: "ADD_FRIEND_RESP",
		3003: "FRIEND_REQUEST_ACTION_REQ",
		3004: "FRIEND_REQUEST_ACTION_RESP",
		3005: "REMOVE_FRIEND_REQ",
		3006: "REMOVE_FRIEND_RESP",
		3007: "GET_FRIEND_LIST_REQ",
		3008: "GET_FRIEND_LIST_RESP",
		3009: "GET_PENDING_REQUESTS_REQ",
		3010: "GET_PENDING_REQUESTS_RESP",
		3011: "BLOCK_USER_REQ",
		3012: "BLOCK_USER_RESP",
		3013: "UNBLOCK_USER_REQ",
		3014: "UNBLOCK_USER_RESP",
		3015: "GET_BLOCKED_LIST_REQ",
		3016: "GET_BLOCKED_LIST_RESP",
		3017: "SET_PRESENCE_REQ",
		3018: "SET_PRESENCE_RESP",
		3019: "GET_PRESENCE_REQ",
		3020: "GET_PRESENCE_RESP",
		3021: "PRESENCE_NOTIFY",
		3022: "FRIEND_REQUEST_NOTIFY",
		3023: "FRIEND_ACCEPTED_NOTIFY",
		3024: "FRIEND_REMOVED_NOTIFY",
		4001: "CREATE_ROOM_REQ",
		4002: "CREATE_ROOM_RESP",
		4003: "JOIN_ROOM_REQ",
		4004: "JOIN_ROOM_RESP",
		4005: "LEAVE_ROOM_REQ",
		4006: "LEAVE_ROOM_RESP",
		4007: "ICE_CANDIDATE_MSG",
		4008: "SDP_OFFER_MSG",
		4009: "SDP_ANSWER_MSG",
		4010: "GET_ROOM_INFO_REQ",
		4011: "GET_ROOM_INFO_RESP",
		4012: "GET_USER_ROOM_REQ",
		4013: "GET_USER_ROOM_RESP",
		4014: "SET_MUTE_REQ",
		4015: "SET_MUTE_RESP",
		4016: "SET_DEAFEN_REQ",
		4017: "SET_DEAFEN_RESP",
		4018: "PARTICIPANT_JOINED_NOTIFY",
		4019: "PARTICIPANT_LEFT_NOTIFY",
		4020: "PARTICIPANT_STATE_CHANGED_NOTIFY",
		4021: "SPEAKING_NOTIFY",
		5001: "SERVER_AUTH_REQ",
		5002: "SERVER_AUTH_RESP",
		5003: "SERVER_HEARTBEAT_PING",
		5004: "SERVER_HEARTBEAT_PONG",
		5005: "INJECT_MESSAGE_REQ",
		5006: "INJECT_MESSAGE_RESP",
		5007: "INJECT_MESSAGE_NOTIFY",
		5008: "EVENT_PUBLISH_REQ",
		5009: "EVENT_PUBLISH_RESP",
		5010: "EVENT_DELIVER_NOTIFY",
		5011: "EVENT_ACK_REQ",
		5012: "EVENT_ACK_RESP",
		5013: "BIND_PLAYER_IDENTITY_REQ",
		5014: "BIND_PLAYER_IDENTITY_RESP",
		5015: "UNBIND_PLAYER_IDENTITY_REQ",
		5016: "UNBIND_PLAYER_IDENTITY_RESP",
		5017: "GET_PLAYER_IDENTITIES_REQ",
		5018: "GET_PLAYER_IDENTITIES_RESP",
		5019: "RESOLVE_GAME_USER_REQ",
		5020: "RESOLVE_GAME_USER_RESP",
		5021: "SUBSCRIBE_PLAYER_CHANNEL_REQ",
		5022: "SUBSCRIBE_PLAYER_CHANNEL_RESP",
		5023: "UNSUBSCRIBE_PLAYER_CHANNEL_REQ",
		5024: "UNSUBSCRIBE_PLAYER_CHANNEL_RESP",
		5025: "GET_PLAYER_SUBSCRIPTIONS_REQ",
		5026: "GET_PLAYER_SUBSCRIPTIONS_RESP",
		5027: "MARK_CHANNELS_READ_REQ",
		5028: "MARK_CHANNELS_READ_RESP",
		5029: "GET_UNREAD_SUMMARY_REQ",
		5030: "GET_UNREAD_SUMMARY_RESP",
		5050: "PEER_REGISTER_REQ",
		5051: "PEER_REGISTER_RESP",
		5052: "CHANNEL_MESSAGE_NOTIFY",
		5053: "PEER_INJECT_MESSAGE_NOTIFY",
		6001: "REGISTER_DEVICE_REQ",
		6002: "REGISTER_DEVICE_RESP",
		6003: "UNREGISTER_DEVICE_REQ",
		6004: "UNREGISTER_DEVICE_RESP",
		6005: "UPDATE_DEVICE_TOKEN_REQ",
		6006: "UPDATE_DEVICE_TOKEN_RESP",
		6007: "GET_USER_DEVICES_REQ",
		6008: "GET_USER_DEVICES_RESP",
		6009: "PUSH_NOTIFICATION_REQ",
		6010: "PUSH_NOTIFICATION_RESP",
		7001: "CREATE_PARTY_REQ",
		7002: "CREATE_PARTY_RESP",
		7003: "DISBAND_PARTY_REQ",
		7004: "DISBAND_PARTY_RESP",
		7005: "INVITE_TO_PARTY_REQ",
		7006: "INVITE_TO_PARTY_RESP",
		7007: "INVITE_NOTIFY",
		7008: "ACCEPT_INVITE_REQ",
		7009: "ACCEPT_INVITE_RESP",
		7010: "DECLINE_INVITE_REQ",
		7011: "DECLINE_INVITE_RESP",
		7012: "INVITE_RESULT_NOTIFY",
		7013: "LEAVE_PARTY_REQ",
		7014: "LEAVE_PARTY_RESP",
		7015: "KICK_PARTY_MEMBER_REQ",
		7016: "KICK_PARTY_MEMBER_RESP",
		7017: "TRANSFER_LEADER_REQ",
		7018: "TRANSFER_LEADER_RESP",
		7019: "SET_READY_REQ",
		7020: "SET_READY_RESP",
		7021: "PARTY_JOINED_NOTIFY",
		7022: "PARTY_LEFT_NOTIFY",
		7023: "PARTY_KICKED_NOTIFY",
		7024: "PARTY_STATE_CHANGED_NOTIFY",
		7025: "PARTY_DISBANDED_NOTIFY",
		7026: "GET_MY_PARTY_REQ",
		7027: "GET_MY_PARTY_RESP",
	}
	MsgID_value = map[string]int32{
		"UNKNOWN":                          0,
		"HEARTBEAT_PING":                   1001,
		"HEARTBEAT_PONG":                   1002,
		"LOGIN_REQ":                        1003,
		"LOGIN_RESP":                       1004,
		"KICK_NOTIFY":                      1005,
		"LOGOUT_REQ":                       1006,
		"LOGOUT_RESP":                      1007,
		"REGISTER_REQ":                     1008,
		"REGISTER_RESP":                    1009,
		"PASSWORD_LOGIN_REQ":               1010,
		"PASSWORD_LOGIN_RESP":              1011,
		"REFRESH_TOKEN_REQ":                1012,
		"REFRESH_TOKEN_RESP":               1013,
		"GET_SESSIONS_REQ":                 1014,
		"GET_SESSIONS_RESP":                1015,
		"REVOKE_SESSION_REQ":               1016,
		"REVOKE_SESSION_RESP":              1017,
		"CHANGE_PASSWORD_REQ":              1018,
		"CHANGE_PASSWORD_RESP":             1019,
		"SEND_MESSAGE_REQ":                 2001,
		"SEND_MESSAGE_RESP":                2002,
		"GET_HISTORY_REQ":                  2003,
		"GET_HISTORY_RESP":                 2004,
		"CHAT_MESSAGE_NOTIFY":              2005,
		"CREATE_GROUP_REQ":                 2101,
		"CREATE_GROUP_RESP":                2102,
		"JOIN_GROUP_REQ":                   2103,
		"JOIN_GROUP_RESP":                  2104,
		"LEAVE_GROUP_REQ":                  2105,
		"LEAVE_GROUP_RESP":                 2106,
		"KICK_MEMBER_REQ":                  2107,
		"KICK_MEMBER_RESP":                 2108,
		"GET_GROUP_INFO_REQ":               2109,
		"GET_GROUP_INFO_RESP":              2110,
		"GET_GROUP_MEMBERS_REQ":            2111,
		"GET_GROUP_MEMBERS_RESP":           2112,
		"GET_USER_GROUPS_REQ":              2113,
		"GET_USER_GROUPS_RESP":             2114,
		"INVITE_TO_GROUP_REQ":              2115,
		"INVITE_TO_GROUP_RESP":             2116,
		"GROUP_CREATED_NOTIFY":             2117,
		"GROUP_MEMBER_JOINED_NOTIFY":       2118,
		"GROUP_MEMBER_LEFT_NOTIFY":         2119,
		"GROUP_MEMBER_KICKED_NOTIFY":       2120,
		"GROUP_UPDATED_NOTIFY":             2121,
		"MARK_READ_REQ":                    2201,
		"MARK_READ_RESP":                   2202,
		"GET_READ_RECEIPTS_REQ":            2203,
		"GET_READ_RECEIPTS_RESP":           2204,
		"GET_UNREAD_COUNT_REQ":             2205,
		"GET_UNREAD_COUNT_RESP":            2206,
		"MESSAGE_READ_NOTIFY":              2207,
		"TYPING_INDICATOR_NOTIFY":          2208,
		"MESSAGE_ACK":                      2209,
		"MESSAGE_NACK":                     2210,
		"TRACK_MESSAGE_REQ":                2211,
		"TRACK_MESSAGE_RESP":               2212,
		"GET_HISTORY_V2_REQ":               2213,
		"GET_HISTORY_V2_RESP":              2214,
		"ADD_REACTION_REQ":                 2215,
		"ADD_REACTION_RESP":                2216,
		"REMOVE_REACTION_REQ":              2217,
		"REMOVE_REACTION_RESP":             2218,
		"GET_REACTIONS_REQ":                2219,
		"GET_REACTIONS_RESP":               2220,
		"REACTION_ADDED_NOTIFY":            2221,
		"REACTION_REMOVED_NOTIFY":          2222,
		"GET_TYPING_USERS_REQ":             2223,
		"GET_TYPING_USERS_RESP":            2224,
		"EDIT_MESSAGE_REQ":                 2225,
		"EDIT_MESSAGE_RESP":                2226,
		"DELETE_MESSAGE_REQ":               2227,
		"DELETE_MESSAGE_RESP":              2228,
		"BULK_DELETE_REQ":                  2229,
		"BULK_DELETE_RESP":                 2230,
		"MESSAGE_EDITED_NOTIFY":            2231,
		"MESSAGE_DELETED_NOTIFY":           2232,
		"GET_MENTION_SUGGESTIONS_REQ":      2233,
		"GET_MENTION_SUGGESTIONS_RESP":     2234,
		"SET_CHANNEL_MUTE_REQ":             2235,
		"SET_CHANNEL_MUTE_RESP":            2236,
		"GET_CHANNEL_MUTES_REQ":            2237,
		"GET_CHANNEL_MUTES_RESP":           2238,
		"ADD_FRIEND_REQ":                   3001,
		"ADD_FRIEND_RESP":                  3002,
		"FRIEND_REQUEST_ACTION_REQ":        3003,
		"FRIEND_REQUEST_ACTION_RESP":       3004,
		"REMOVE_FRIEND_REQ":                3005,
		"REMOVE_FRIEND_RESP":               3006,
		"GET_FRIEND_LIST_REQ":              3007,
		"GET_FRIEND_LIST_RESP":             3008,
		"GET_PENDING_REQUESTS_REQ":         3009,
		"GET_PENDING_REQUESTS_RESP":        3010,
		"BLOCK_USER_REQ":                   3011,
		"BLOCK_USER_RESP":                  3012,
		"UNBLOCK_USER_REQ":                 3013,
		"UNBLOCK_USER_RESP":                3014,
		"GET_BLOCKED_LIST_REQ":             3015,
		"GET_BLOCKED_LIST_RESP":            3016,
		"SET_PRESENCE_REQ":                 3017,
		"SET_PRESENCE_RESP":                3018,
		"GET_PRESENCE_REQ":                 3019,
		"GET_PRESENCE_RESP":                3020,
		"PRESENCE_NOTIFY":                  3021,
		"FRIEND_REQUEST_NOTIFY":            3022,
		"FRIEND_ACCEPTED_NOTIFY":           3023,
		"FRIEND_REMOVED_NOTIFY":            3024,
		"CREATE_ROOM_REQ":                  4001,
		"CREATE_ROOM_RESP":                 4002,
		"JOIN_ROOM_REQ":                    4003,
		"JOIN_ROOM_RESP":                   4004,
		"LEAVE_ROOM_REQ":                   4005,
		"LEAVE_ROOM_RESP":                  4006,
		"ICE_CANDIDATE_MSG":                4007,
		"SDP_OFFER_MSG":                    4008,
		"SDP_ANSWER_MSG":                   4009,
		"GET_ROOM_INFO_REQ":                4010,
		"GET_ROOM_INFO_RESP":               4011,
		"GET_USER_ROOM_REQ":                4012,
		"GET_USER_ROOM_RESP":               4013,
		"SET_MUTE_REQ":                     4014,
		"SET_MUTE_RESP":                    4015,
		"SET_DEAFEN_REQ":                   4016,
		"SET_DEAFEN_RESP":                  4017,
		"PARTICIPANT_JOINED_NOTIFY":        4018,
		"PARTICIPANT_LEFT_NOTIFY":          4019,
		"PARTICIPANT_STATE_CHANGED_NOTIFY": 4020,
		"SPEAKING_NOTIFY":                  4021,
		"SERVER_AUTH_REQ":                  5001,
		"SERVER_AUTH_RESP":                 5002,
		"SERVER_HEARTBEAT_PING":            5003,
		"SERVER_HEARTBEAT_PONG":            5004,
		"INJECT_MESSAGE_REQ":               5005,
		"INJECT_MESSAGE_RESP":              5006,
		"INJECT_MESSAGE_NOTIFY":            5007,
		"EVENT_PUBLISH_REQ":                5008,
		"EVENT_PUBLISH_RESP":               5009,
		"EVENT_DELIVER_NOTIFY":             5010,
		"EVENT_ACK_REQ":                    5011,
		"EVENT_ACK_RESP":                   5012,
		"BIND_PLAYER_IDENTITY_REQ":         5013,
		"BIND_PLAYER_IDENTITY_RESP":        5014,
		"UNBIND_PLAYER_IDENTITY_REQ":       5015,
		"UNBIND_PLAYER_IDENTITY_RESP":      5016,
		"GET_PLAYER_IDENTITIES_REQ":        5017,
		"GET_PLAYER_IDENTITIES_RESP":       5018,
		"RESOLVE_GAME_USER_REQ":            5019,
		"RESOLVE_GAME_USER_RESP":           5020,
		"SUBSCRIBE_PLAYER_CHANNEL_REQ":     5021,
		"SUBSCRIBE_PLAYER_CHANNEL_RESP":    5022,
		"UNSUBSCRIBE_PLAYER_CHANNEL_REQ":   5023,
		"UNSUBSCRIBE_PLAYER_CHANNEL_RESP":  5024,
		"GET_PLAYER_SUBSCRIPTIONS_REQ":     5025,
		"GET_PLAYER_SUBSCRIPTIONS_RESP":    5026,
		"MARK_CHANNELS_READ_REQ":           5027,
		"MARK_CHANNELS_READ_RESP":          5028,
		"GET_UNREAD_SUMMARY_REQ":           5029,
		"GET_UNREAD_SUMMARY_RESP":          5030,
		"PEER_REGISTER_REQ":                5050,
		"PEER_REGISTER_RESP":               5051,
		"CHANNEL_MESSAGE_NOTIFY":           5052,
		"PEER_INJECT_MESSAGE_NOTIFY":       5053,
		"REGISTER_DEVICE_REQ":              6001,
		"REGISTER_DEVICE_RESP":             6002,
		"UNREGISTER_DEVICE_REQ":            6003,
		"UNREGISTER_DEVICE_RESP":           6004,
		"UPDATE_DEVICE_TOKEN_REQ":          6005,
		"UPDATE_DEVICE_TOKEN_RESP":         6006,
		"GET_USER_DEVICES_REQ":             6007,
		"GET_USER_DEVICES_RESP":            6008,
		"PUSH_NOTIFICATION_REQ":            6009,
		"PUSH_NOTIFICATION_RESP":           6010,
		"CREATE_PARTY_REQ":                 7001,
		"CREATE_PARTY_RESP":                7002,
		"DISBAND_PARTY_REQ":                7003,
		"DISBAND_PARTY_RESP":               7004,
		"INVITE_TO_PARTY_REQ":              7005,
		"INVITE_TO_PARTY_RESP":             7006,
		"INVITE_NOTIFY":                    7007,
		"ACCEPT_INVITE_REQ":                7008,
		"ACCEPT_INVITE_RESP":               7009,
		"DECLINE_INVITE_REQ":               7010,
		"DECLINE_INVITE_RESP":              7011,
		"INVITE_RESULT_NOTIFY":             7012,
		"LEAVE_PARTY_REQ":                  7013,
		"LEAVE_PARTY_RESP":                 7014,
		"KICK_PARTY_MEMBER_REQ":            7015,
		"KICK_PARTY_MEMBER_RESP":           7016,
		"TRANSFER_LEADER_REQ":              7017,
		"TRANSFER_LEADER_RESP":             7018,
		"SET_READY_REQ":                    7019,
		"SET_READY_RESP":                   7020,
		"PARTY_JOINED_NOTIFY":              7021,
		"PARTY_LEFT_NOTIFY":                7022,
		"PARTY_KICKED_NOTIFY":              7023,
		"PARTY_STATE_CHANGED_NOTIFY":       7024,
		"PARTY_DISBANDED_NOTIFY":           7025,
		"GET_MY_PARTY_REQ":                 7026,
		"GET_MY_PARTY_RESP":                7027,
	}
)

func (x MsgID) Enum() *MsgID {
	p := new(MsgID)
	*p = x
	return p
}

func (x MsgID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgID) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gateway_proto_enumTypes[0].Descriptor()
}

func (MsgID) Type() protoreflect.EnumType {
	return &file_proto_gateway_proto_enumTypes[0]
}

func (x MsgID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgID.Descriptor instead.
func (MsgID) EnumDescriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{0}
}

// Capability bits exchanged during the handshake. The negotiated set is the
// intersection of both sides; anything outside it stays disabled for the
// session. New capabilities bump protocol_version and add a bit - old peers
// that do not know the bit simply never use it.
type PeerCapability int32

const (
	PeerCapability_RELAY_READ_RECEIPTS    PeerCapability = 0
	PeerCapability_RELAY_TYPING           PeerCapability = 1
	PeerCapability_RELAY_PRESENCE         PeerCapability = 2
	PeerCapability_RELAY_OFFLINE_MESSAGES PeerCapability = 3
)

// Enum value maps for PeerCapability.
var (
	PeerCapability_name = map[int32]string{
		0: "RELAY_READ_RECEIPTS",
		1: "RELAY_TYPING",
		2: "RELAY_PRESENCE",
		3: "RELAY_OFFLINE_MESSAGES",
	}
	PeerCapability_value = map[string]int32{
		"RELAY_READ_RECEIPTS":    0,
		"RELAY_TYPING":           1,
		"RELAY_PRESENCE":         2,
		"RELAY_OFFLINE_MESSAGES": 3,
	}
)

func (x PeerCapability) Enum() *PeerCapability {
	p := new(PeerCapability)
	*p = x
	return p
}

func (x PeerCapability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerCapability) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gateway_proto_enumTypes[1].Descriptor()
}

func (PeerCapability) Type() protoreflect.EnumType {
	return &file_proto_gateway_proto_enumTypes[1]
}

func (x PeerCapability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerCapability.Descriptor instead.
func (PeerCapability) EnumDescriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{1}
}

// Universal Packet Envelope (Optional, if we want full protobuf wrap)
// Usually we use Length-Prefixed + Raw Bytes for Body,
// but for simplicity in some SDKs, a full envelope is used.
type Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         MsgID                  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3,enum=chirp.gateway.MsgID" json:"msg_id,omitempty"`
	Sequence      int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_proto_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetMsgId() MsgID {
	if x != nil {
		return x.MsgId
	}
	return MsgID_UNKNOWN
}

func (x *Packet) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Packet) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type HeartbeatPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPing) Reset() {
	*x = HeartbeatPing{}
	mi := &file_proto_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPing) ProtoMessage() {}

func (x *HeartbeatPing) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPing.ProtoReflect.Descriptor instead.
func (*HeartbeatPing) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatPing) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeartbeatPong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPong) Reset() {
	*x = HeartbeatPong{}
	mi := &file_proto_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPong) ProtoMessage() {}

func (x *HeartbeatPong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPong.ProtoReflect.Descriptor instead.
func (*HeartbeatPong) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatPong) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatPong) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type PeerRegisterReq struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ServiceId string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"` // e.g. "game_42"; second registration with the
	// same id displaces the first connection
	ServiceSecret string `protobuf:"bytes,2,opt,name=service_secret,json=serviceSecret,proto3" json:"service_secret,omitempty"` // shared secret for this peer (checked against
	// the hub's --allowed_peers list)
	ProtocolVersion int32  `protobuf:"varint,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // negotiated down to min(hub, spoke)
	GameId          string `protobuf:"bytes,4,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`                             // namespace for this peer's channels; must not
	// contain ':' (it prefixes "<game_id>:" on the
	// hub side)
	SupportedFeatures []PeerCapability `protobuf:"varint,5,rep,packed,name=supported_features,json=supportedFeatures,proto3,enum=chirp.gateway.PeerCapability" json:"supported_features,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PeerRegisterReq) Reset() {
	*x = PeerRegisterReq{}
	mi := &file_proto_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerRegisterReq) ProtoMessage() {}

func (x *PeerRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerRegisterReq.ProtoReflect.Descriptor instead.
func (*PeerRegisterReq) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *PeerRegisterReq) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *PeerRegisterReq) GetServiceSecret() string {
	if x != nil {
		return x.ServiceSecret
	}
	return ""
}

func (x *PeerRegisterReq) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *PeerRegisterReq) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PeerRegisterReq) GetSupportedFeatures() []PeerCapability {
	if x != nil {
		return x.SupportedFeatures
	}
	return nil
}

type PeerRegisterResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  common.ErrorCode       `protobuf:"varint,1,opt,name=code,proto3,enum=chirp.common.ErrorCode" json:"code,omitempty"` // OK / AUTH_FAILED (not whitelisted) /
	// VERSION_MISMATCH (below min version)
	ProtocolVersion int32 `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // negotiated version (OK) or hub's
	// current version (mismatch)
	MinVersion               int32 `protobuf:"varint,3,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`                                             // hub's minimum accepted version
	HeartbeatIntervalSeconds int32 `protobuf:"varint,4,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"` // hub-assigned cadence; a peer that
	// stays silent for ~2x is dropped
	SupportedFeatures []PeerCapability `protobuf:"varint,5,rep,packed,name=supported_features,json=supportedFeatures,proto3,enum=chirp.gateway.PeerCapability" json:"supported_features,omitempty"` // negotiated intersection
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PeerRegisterResp) Reset() {
	*x = PeerRegisterResp{}
	mi := &file_proto_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerRegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerRegisterResp) ProtoMessage() {}

func (x *PeerRegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerRegisterResp.ProtoReflect.Descriptor instead.
func (*PeerRegisterResp) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *PeerRegisterResp) GetCode() common.ErrorCode {
	if x != nil {
		return x.Code
	}
	return common.ErrorCode(0)
}

func (x *PeerRegisterResp) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *PeerRegisterResp) GetMinVersion() int32 {
	if x != nil {
		return x.MinVersion
	}
	return 0
}

func (x *PeerRegisterResp) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *PeerRegisterResp) GetSupportedFeatures() []PeerCapability {
	if x != nil {
		return x.SupportedFeatures
	}
	return nil
}

// Spoke -> hub: one game-side channel message, fanned out by the hub to every
// subscribed App player as an injected private copy named
// "<game_id>:<channel_id>". The message body is the game-side ChatMessage
// verbatim; channel_id stays bare (the hub adds the prefix).
type ChannelMessageNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"` // redundant with the registration for validation
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Message       *chat.ChatMessage      `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelMessageNotify) Reset() {
	*x = ChannelMessageNotify{}
	mi := &file_proto_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelMessageNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelMessageNotify) ProtoMessage() {}

func (x *ChannelMessageNotify) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelMessageNotify.ProtoReflect.Descriptor instead.
func (*ChannelMessageNotify) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *ChannelMessageNotify) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ChannelMessageNotify) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChannelMessageNotify) GetMessage() *chat.ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

// Hub -> spoke: an App player's reply to a "<game_id>:<channel_id>" channel,
// injected into the game-side channel as a normal message. The spoke never
// sees the App player's player_id - the hub resolves it to a game_user_id
// before sending.
type PeerInjectMessageNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"` // bare game-side channel id
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`    // game_user_id resolved from the App player
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ClientMsgId   string                 `protobuf:"bytes,4,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"` // optional idempotency key from the App client
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInjectMessageNotify) Reset() {
	*x = PeerInjectMessageNotify{}
	mi := &file_proto_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInjectMessageNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInjectMessageNotify) ProtoMessage() {}

func (x *PeerInjectMessageNotify) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInjectMessageNotify.ProtoReflect.Descriptor instead.
func (*PeerInjectMessageNotify) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *PeerInjectMessageNotify) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *PeerInjectMessageNotify) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *PeerInjectMessageNotify) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *PeerInjectMessageNotify) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

var File_proto_gateway_proto protoreflect.FileDescriptor

const file_proto_gateway_proto_rawDesc = "" +
	"\n" +
	"\x13proto/gateway.proto\x12\rchirp.gateway\x1a\x12proto/common.proto\x1a\x10proto/chat.proto\"e\n" +
	"\x06Packet\x12+\n" +
	"\x06msg_id\x18\x01 \x01(\x0e2\x14.chirp.gateway.MsgIDR\x05msgId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\"-\n" +
	"\rHeartbeatPing\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"N\n" +
	"\rHeartbeatPong\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\"\xe9\x01\n" +
	"\x0fPeerRegisterReq\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12%\n" +
	"\x0eservice_secret\x18\x02 \x01(\tR\rserviceSecret\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\x05R\x0fprotocolVersion\x12\x17\n" +
	"\agame_id\x18\x04 \x01(\tR\x06gameId\x12L\n" +
	"\x12supported_features\x18\x05 \x03(\x0e2\x1d.chirp.gateway.PeerCapabilityR\x11supportedFeatures\"\x97\x02\n" +
	"\x10PeerRegisterResp\x12+\n" +
	"\x04code\x18\x01 \x01(\x0e2\x17.chirp.common.ErrorCodeR\x04code\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\x05R\x0fprotocolVersion\x12\x1f\n" +
	"\vmin_version\x18\x03 \x01(\x05R\n" +
	"minVersion\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x04 \x01(\x05R\x18heartbeatIntervalSeconds\x12L\n" +
	"\x12supported_features\x18\x05 \x03(\x0e2\x1d.chirp.gateway.PeerCapabilityR\x11supportedFeatures\"\x81\x01\n" +
	"\x14ChannelMessageNotify\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x121\n" +
	"\amessage\x18\x03 \x01(\v2\x17.chirp.chat.ChatMessageR\amessage\"\x93\x01\n" +
	"\x17PeerInjectMessageNotify\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\"\n" +
	"\rclient_msg_id\x18\x04 \x01(\tR\vclientMsgId*\xa9(\n" +
	"\x05MsgID\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x13\n" +
	"\x0eHEARTBEAT_PING\x10\xe9\a\x12\x13\n" +
	"\x0eHEARTBEAT_PONG\x10\xea\a\x12\x0e\n" +
	"\tLOGIN_REQ\x10\xeb\a\x12\x0f\n" +
	"\n" +
	"LOGIN_RESP\x10\xec\a\x12\x10\n" +
	"\vKICK_NOTIFY\x10\xed\a\x12\x0f\n" +
	"\n" +
	"LOGOUT_REQ\x10\xee\a\x12\x10\n" +
	"\vLOGOUT_RESP\x10\xef\a\x12\x11\n" +
	"\fREGISTER_REQ\x10\xf0\a\x12\x12\n" +
	"\rREGISTER_RESP\x10\xf1\a\x12\x17\n" +
	"\x12PASSWORD_LOGIN_REQ\x10\xf2\a\x12\x18\n" +
	"\x13PASSWORD_LOGIN_RESP\x10\xf3\a\x12\x16\n" +
	"\x11REFRESH_TOKEN_REQ\x10\xf4\a\x12\x17\n" +
	"\x12REFRESH_TOKEN_RESP\x10\xf5\a\x12\x15\n" +
	"\x10GET_SESSIONS_REQ\x10\xf6\a\x12\x16\n" +
	"\x11GET_SESSIONS_RESP\x10\xf7\a\x12\x17\n" +
	"\x12REVOKE_SESSION_REQ\x10\xf8\a\x12\x18\n" +
	"\x13REVOKE_SESSION_RESP\x10\xf9\a\x12\x18\n" +
	"\x13CHANGE_PASSWORD_REQ\x10\xfa\a\x12\x19\n" +
	"\x14CHANGE_PASSWORD_RESP\x10\xfb\a\x12\x15\n" +
	"\x10SEND_MESSAGE_REQ\x10\xd1\x0f\x12\x16\n" +
	"\x11SEND_MESSAGE_RESP\x10\xd2\x0f\x12\x14\n" +
	"\x0fGET_HISTORY_REQ\x10\xd3\x0f\x12\x15\n" +
	"\x10GET_HISTORY_RESP\x10\xd4\x0f\x12\x18\n" +
	"\x13CHAT_MESSAGE_NOTIFY\x10\xd5\x0f\x12\x15\n" +
	"\x10CREATE_GROUP_REQ\x10\xb5\x10\x12\x16\n" +
	"\x11CREATE_GROUP_RESP\x10\xb6\x10\x12\x13\n" +
	"\x0eJOIN_GROUP_REQ\x10\xb7\x10\x12\x14\n" +
	"\x0fJOIN_GROUP_RESP\x10\xb8\x10\x12\x14\n" +
	"\x0fLEAVE_GROUP_REQ\x10\xb9\x10\x12\x15\n" +
	"\x10LEAVE_GROUP_RESP\x10\xba\x10\x12\x14\n" +
	"\x0fKICK_MEMBER_REQ\x10\xbb\x10\x12\x15\n" +
	"\x10KICK_MEMBER_RESP\x10\xbc\x10\x12\x17\n" +
	"\x12GET_GROUP_INFO_REQ\x10\xbd\x10\x12\x18\n" +
	"\x13GET_GROUP_INFO_RESP\x10\xbe\x10\x12\x1a\n" +
	"\x15GET_GROUP_MEMBERS_REQ\x10\xbf\x10\x12\x1b\n" +
	"\x16GET_GROUP_MEMBERS_RESP\x10\xc0\x10\x12\x18\n" +
	"\x13GET_USER_GROUPS_REQ\x10\xc1\x10\x12\x19\n" +
	"\x14GET_USER_GROUPS_RESP\x10\xc2\x10\x12\x18\n" +
	"\x13INVITE_TO_GROUP_REQ\x10\xc3\x10\x12\x19\n" +
	"\x14INVITE_TO_GROUP_RESP\x10\xc4\x10\x12\x19\n" +
	"\x14GROUP_CREATED_NOTIFY\x10\xc5\x10\x12\x1f\n" +
	"\x1aGROUP_MEMBER_JOINED_NOTIFY\x10\xc6\x10\x12\x1d\n" +
	"\x18GROUP_MEMBER_LEFT_NOTIFY\x10\xc7\x10\x12\x1f\n" +
	"\x1aGROUP_MEMBER_KICKED_NOTIFY\x10\xc8\x10\x12\x19\n" +
	"\x14GROUP_UPDATED_NOTIFY\x10\xc9\x10\x12\x12\n" +
	"\rMARK_READ_REQ\x10\x99\x11\x12\x13\n" +
	"\x0eMARK_READ_RESP\x10\x9a\x11\x12\x1a\n" +
	"\x15GET_READ_RECEIPTS_REQ\x10\x9b\x11\x12\x1b\n" +
	"\x16GET_READ_RECEIPTS_RESP\x10\x9c\x11\x12\x19\n" +
	"\x14GET_UNREAD_COUNT_REQ\x10\x9d\x11\x12\x1a\n" +
	"\x15GET_UNREAD_COUNT_RESP\x10\x9e\x11\x12\x18\n" +
	"\x13MESSAGE_READ_NOTIFY\x10\x9f\x11\x12\x1c\n" +
	"\x17TYPING_INDICATOR_NOTIFY\x10\xa0\x11\x12\x10\n" +
	"\vMESSAGE_ACK\x10\xa1\x11\x12\x11\n" +
	"\fMESSAGE_NACK\x10\xa2\x11\x12\x16\n" +
	"\x11TRACK_MESSAGE_REQ\x10\xa3\x11\x12\x17\n" +
	"\x12TRACK_MESSAGE_RESP\x10\xa4\x11\x12\x17\n" +
	"\x12GET_HISTORY_V2_REQ\x10\xa5\x11\x12\x18\n" +
	"\x13GET_HISTORY_V2_RESP\x10\xa6\x11\x12\x15\n" +
	"\x10ADD_REACTION_REQ\x10\xa7\x11\x12\x16\n" +
	"\x11ADD_REACTION_RESP\x10\xa8\x11\x12\x18\n" +
	"\x13REMOVE_REACTION_REQ\x10\xa9\x11\x12\x19\n" +
	"\x14REMOVE_REACTION_RESP\x10\xaa\x11\x12\x16\n" +
	"\x11GET_REACTIONS_REQ\x10\xab\x11\x12\x17\n" +
	"\x12GET_REACTIONS_RESP\x10\xac\x11\x12\x1a\n" +
	"\x15REACTION_ADDED_NOTIFY\x10\xad\x11\x12\x1c\n" +
	"\x17REACTION_REMOVED_NOTIFY\x10\xae\x11\x12\x19\n" +
	"\x14GET_TYPING_USERS_REQ\x10\xaf\x11\x12\x1a\n" +
	"\x15GET_TYPING_USERS_RESP\x10\xb0\x11\x12\x15\n" +
	"\x10EDIT_MESSAGE_REQ\x10\xb1\x11\x12\x16\n" +
	"\x11EDIT_MESSAGE_RESP\x10\xb2\x11\x12\x17\n" +
	"\x12DELETE_MESSAGE_REQ\x10\xb3\x11\x12\x18\n" +
	"\x13DELETE_MESSAGE_RESP\x10\xb4\x11\x12\x14\n" +
	"\x0fBULK_DELETE_REQ\x10\xb5\x11\x12\x15\n" +
	"\x10BULK_DELETE_RESP\x10\xb6\x11\x12\x1a\n" +
	"\x15MESSAGE_EDITED_NOTIFY\x10\xb7\x11\x12\x1b\n" +
	"\x16MESSAGE_DELETED_NOTIFY\x10\xb8\x11\x12 \n" +
	"\x1bGET_MENTION_SUGGESTIONS_REQ\x10\xb9\x11\x12!\n" +
	"\x1cGET_MENTION_SUGGESTIONS_RESP\x10\xba\x11\x12\x19\n" +
	"\x14SET_CHANNEL_MUTE_REQ\x10\xbb\x11\x12\x1a\n" +
	"\x15SET_CHANNEL_MUTE_RESP\x10\xbc\x11\x12\x1a\n" +
	"\x15GET_CHANNEL_MUTES_REQ\x10\xbd\x11\x12\x1b\n" +
	"\x16GET_CHANNEL_MUTES_RESP\x10\xbe\x11\x12\x13\n" +
	"\x0eADD_FRIEND_REQ\x10\xb9\x17\x12\x14\n" +
	"\x0fADD_FRIEND_RESP\x10\xba\x17\x12\x1e\n" +
	"\x19FRIEND_REQUEST_ACTION_REQ\x10\xbb\x17\x12\x1f\n" +
	"\x1aFRIEND_REQUEST_ACTION_RESP\x10\xbc\x17\x12\x16\n" +
	"\x11REMOVE_FRIEND_REQ\x10\xbd\x17\x12\x17\n" +
	"\x12REMOVE_FRIEND_RESP\x10\xbe\x17\x12\x18\n" +
	"\x13GET_FRIEND_LIST_REQ\x10\xbf\x17\x12\x19\n" +
	"\x14GET_FRIEND_LIST_RESP\x10\xc0\x17\x12\x1d\n" +
	"\x18GET_PENDING_REQUESTS_REQ\x10\xc1\x17\x12\x1e\n" +
	"\x19GET_PENDING_REQUESTS_RESP\x10\xc2\x17\x12\x13\n" +
	"\x0eBLOCK_USER_REQ\x10\xc3\x17\x12\x14\n" +
	"\x0fBLOCK_USER_RESP\x10\xc4\x17\x12\x15\n" +
	"\x10UNBLOCK_USER_REQ\x10\xc5\x17\x12\x16\n" +
	"\x11UNBLOCK_USER_RESP\x10\xc6\x17\x12\x19\n" +
	"\x14GET_BLOCKED_LIST_REQ\x10\xc7\x17\x12\x1a\n" +
	"\x15GET_BLOCKED_LIST_RESP\x10\xc8\x17\x12\x15\n" +
	"\x10SET_PRESENCE_REQ\x10\xc9\x17\x12\x16\n" +
	"\x11SET_PRESENCE_RESP\x10\xca\x17\x12\x15\n" +
	"\x10GET_PRESENCE_REQ\x10\xcb\x17\x12\x16\n" +
	"\x11GET_PRESENCE_RESP\x10\xcc\x17\x12\x14\n" +
	"\x0fPRESENCE_NOTIFY\x10\xcd\x17\x12\x1a\n" +
	"\x15FRIEND_REQUEST_NOTIFY\x10\xce\x17\x12\x1b\n" +
	"\x16FRIEND_ACCEPTED_NOTIFY\x10\xcf\x17\x12\x1a\n" +
	"\x15FRIEND_REMOVED_NOTIFY\x10\xd0\x17\x12\x14\n" +
	"\x0fCREATE_ROOM_REQ\x10\xa1\x1f\x12\x15\n" +
	"\x10CREATE_ROOM_RESP\x10\xa2\x1f\x12\x12\n" +
	"\rJOIN_ROOM_REQ\x10\xa3\x1f\x12\x13\n" +
	"\x0eJOIN_ROOM_RESP\x10\xa4\x1f\x12\x13\n" +
	"\x0eLEAVE_ROOM_REQ\x10\xa5\x1f\x12\x14\n" +
	"\x0fLEAVE_ROOM_RESP\x10\xa6\x1f\x12\x16\n" +
	"\x11ICE_CANDIDATE_MSG\x10\xa7\x1f\x12\x12\n" +
	"\rSDP_OFFER_MSG\x10\xa8\x1f\x12\x13\n" +
	"\x0eSDP_ANSWER_MSG\x10\xa9\x1f\x12\x16\n" +
	"\x11GET_ROOM_INFO_REQ\x10\xaa\x1f\x12\x17\n" +
	"\x12GET_ROOM_INFO_RESP\x10\xab\x1f\x12\x16\n" +
	"\x11GET_USER_ROOM_REQ\x10\xac\x1f\x12\x17\n" +
	"\x12GET_USER_ROOM_RESP\x10\xad\x1f\x12\x11\n" +
	"\fSET_MUTE_REQ\x10\xae\x1f\x12\x12\n" +
	"\rSET_MUTE_RESP\x10\xaf\x1f\x12\x13\n" +
	"\x0eSET_DEAFEN_REQ\x10\xb0\x1f\x12\x14\n" +
	"\x0fSET_DEAFEN_RESP\x10\xb1\x1f\x12\x1e\n" +
	"\x19PARTICIPANT_JOINED_NOTIFY\x10\xb2\x1f\x12\x1c\n" +
	"\x17PARTICIPANT_LEFT_NOTIFY\x10\xb3\x1f\x12%\n" +
	" PARTICIPANT_STATE_CHANGED_NOTIFY\x10\xb4\x1f\x12\x14\n" +
	"\x0fSPEAKING_NOTIFY\x10\xb5\x1f\x12\x14\n" +
	"\x0fSERVER_AUTH_REQ\x10\x89'\x12\x15\n" +
	"\x10SERVER_AUTH_RESP\x10\x8a'\x12\x1a\n" +
	"\x15SERVER_HEARTBEAT_PING\x10\x8b'\x12\x1a\n" +
	"\x15SERVER_HEARTBEAT_PONG\x10\x8c'\x12\x17\n" +
	"\x12INJECT_MESSAGE_REQ\x10\x8d'\x12\x18\n" +
	"\x13INJECT_MESSAGE_RESP\x10\x8e'\x12\x1a\n" +
	"\x15INJECT_MESSAGE_NOTIFY\x10\x8f'\x12\x16\n" +
	"\x11EVENT_PUBLISH_REQ\x10\x90'\x12\x17\n" +
	"\x12EVENT_PUBLISH_RESP\x10\x91'\x12\x19\n" +
	"\x14EVENT_DELIVER_NOTIFY\x10\x92'\x12\x12\n" +
	"\rEVENT_ACK_REQ\x10\x93'\x12\x13\n" +
	"\x0eEVENT_ACK_RESP\x10\x94'\x12\x1d\n" +
	"\x18BIND_PLAYER_IDENTITY_REQ\x10\x95'\x12\x1e\n" +
	"\x19BIND_PLAYER_IDENTITY_RESP\x10\x96'\x12\x1f\n" +
	"\x1aUNBIND_PLAYER_IDENTITY_REQ\x10\x97'\x12 \n" +
	"\x1bUNBIND_PLAYER_IDENTITY_RESP\x10\x98'\x12\x1e\n" +
	"\x19GET_PLAYER_IDENTITIES_REQ\x10\x99'\x12\x1f\n" +
	"\x1aGET_PLAYER_IDENTITIES_RESP\x10\x9a'\x12\x1a\n" +
	"\x15RESOLVE_GAME_USER_REQ\x10\x9b'\x12\x1b\n" +
	"\x16RESOLVE_GAME_USER_RESP\x10\x9c'\x12!\n" +
	"\x1cSUBSCRIBE_PLAYER_CHANNEL_REQ\x10\x9d'\x12\"\n" +
	"\x1dSUBSCRIBE_PLAYER_CHANNEL_RESP\x10\x9e'\x12#\n" +
	"\x1eUNSUBSCRIBE_PLAYER_CHANNEL_REQ\x10\x9f'\x12$\n" +
	"\x1fUNSUBSCRIBE_PLAYER_CHANNEL_RESP\x10\xa0'\x12!\n" +
	"\x1cGET_PLAYER_SUBSCRIPTIONS_REQ\x10\xa1'\x12\"\n" +
	"\x1dGET_PLAYER_SUBSCRIPTIONS_RESP\x10\xa2'\x12\x1b\n" +
	"\x16MARK_CHANNELS_READ_REQ\x10\xa3'\x12\x1c\n" +
	"\x17MARK_CHANNELS_READ_RESP\x10\xa4'\x12\x1b\n" +
	"\x16GET_UNREAD_SUMMARY_REQ\x10\xa5'\x12\x1c\n" +
	"\x17GET_UNREAD_SUMMARY_RESP\x10\xa6'\x12\x16\n" +
	"\x11PEER_REGISTER_REQ\x10\xba'\x12\x17\n" +
	"\x12PEER_REGISTER_RESP\x10\xbb'\x12\x1b\n" +
	"\x16CHANNEL_MESSAGE_NOTIFY\x10\xbc'\x12\x1f\n" +
	"\x1aPEER_INJECT_MESSAGE_NOTIFY\x10\xbd'\x12\x18\n" +
	"\x13REGISTER_DEVICE_REQ\x10\xf1.\x12\x19\n" +
	"\x14REGISTER_DEVICE_RESP\x10\xf2.\x12\x1a\n" +
	"\x15UNREGISTER_DEVICE_REQ\x10\xf3.\x12\x1b\n" +
	"\x16UNREGISTER_DEVICE_RESP\x10\xf4.\x12\x1c\n" +
	"\x17UPDATE_DEVICE_TOKEN_REQ\x10\xf5.\x12\x1d\n" +
	"\x18UPDATE_DEVICE_TOKEN_RESP\x10\xf6.\x12\x19\n" +
	"\x14GET_USER_DEVICES_REQ\x10\xf7.\x12\x1a\n" +
	"\x15GET_USER_DEVICES_RESP\x10\xf8.\x12\x1a\n" +
	"\x15PUSH_NOTIFICATION_REQ\x10\xf9.\x12\x1b\n" +
	"\x16PUSH_NOTIFICATION_RESP\x10\xfa.\x12\x15\n" +
	"\x10CREATE_PARTY_REQ\x10\xd96\x12\x16\n" +
	"\x11CREATE_PARTY_RESP\x10\xda6\x12\x16\n" +
	"\x11DISBAND_PARTY_REQ\x10\xdb6\x12\x17\n" +
	"\x12DISBAND_PARTY_RESP\x10\xdc6\x12\x18\n" +
	"\x13INVITE_TO_PARTY_REQ\x10\xdd6\x12\x19\n" +
	"\x14INVITE_TO_PARTY_RESP\x10\xde6\x12\x12\n" +
	"\rINVITE_NOTIFY\x10\xdf6\x12\x16\n" +
	"\x11ACCEPT_INVITE_REQ\x10\xe06\x12\x17\n" +
	"\x12ACCEPT_INVITE_RESP\x10\xe16\x12\x17\n" +
	"\x12DECLINE_INVITE_REQ\x10\xe26\x12\x18\n" +
	"\x13DECLINE_INVITE_RESP\x10\xe36\x12\x19\n" +
	"\x14INVITE_RESULT_NOTIFY\x10\xe46\x12\x14\n" +
	"\x0fLEAVE_PARTY_REQ\x10\xe56\x12\x15\n" +
	"\x10LEAVE_PARTY_RESP\x10\xe66\x12\x1a\n" +
	"\x15KICK_PARTY_MEMBER_REQ\x10\xe76\x12\x1b\n" +
	"\x16KICK_PARTY_MEMBER_RESP\x10\xe86\x12\x18\n" +
	"\x13TRANSFER_LEADER_REQ\x10\xe96\x12\x19\n" +
	"\x14TRANSFER_LEADER_RESP\x10\xea6\x12\x12\n" +
	"\rSET_READY_REQ\x10\xeb6\x12\x13\n" +
	"\x0eSET_READY_RESP\x10\xec6\x12\x18\n" +
	"\x13PARTY_JOINED_NOTIFY\x10\xed6\x12\x16\n" +
	"\x11PARTY_LEFT_NOTIFY\x10\xee6\x12\x18\n" +
	"\x13PARTY_KICKED_NOTIFY\x10\xef6\x12\x1f\n" +
	"\x1aPARTY_STATE_CHANGED_NOTIFY\x10\xf06\x12\x1b\n" +
	"\x16PARTY_DISBANDED_NOTIFY\x10\xf16\x12\x15\n" +
	"\x10GET_MY_PARTY_REQ\x10\xf26\x12\x16\n" +
	"\x11GET_MY_PARTY_RESP\x10\xf36*k\n" +
	"\x0ePeerCapability\x12\x17\n" +
	"\x13RELAY_READ_RECEIPTS\x10\x00\x12\x10\n" +
	"\fRELAY_TYPING\x10\x01\x12\x12\n" +
	"\x0eRELAY_PRESENCE\x10\x02\x12\x1a\n" +
	"\x16RELAY_OFFLINE_MESSAGES\x10\x03B'Z%github.com/cui/chirp/proto/go/gatewayb\x06proto3"

var (
	file_proto_gateway_proto_rawDescOnce sync.Once
	file_proto_gateway_proto_rawDescData []byte
)

func file_proto_gateway_proto_rawDescGZIP() []byte {
	file_proto_gateway_proto_rawDescOnce.Do(func() {
		file_proto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_rawDesc)))
	})
	return file_proto_gateway_proto_rawDescData
}

var file_proto_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_gateway_proto_goTypes = []any{
	(MsgID)(0),                      // 0: chirp.gateway.MsgID
	(PeerCapability)(0),             // 1: chirp.gateway.PeerCapability
	(*Packet)(nil),                  // 2: chirp.gateway.Packet
	(*HeartbeatPing)(nil),           // 3: chirp.gateway.HeartbeatPing
	(*HeartbeatPong)(nil),           // 4: chirp.gateway.HeartbeatPong
	(*PeerRegisterReq)(nil),         // 5: chirp.gateway.PeerRegisterReq
	(*PeerRegisterResp)(nil),        // 6: chirp.gateway.PeerRegisterResp
	(*ChannelMessageNotify)(nil),    // 7: chirp.gateway.ChannelMessageNotify
	(*PeerInjectMessageNotify)(nil), // 8: chirp.gateway.PeerInjectMessageNotify
	(common.ErrorCode)(0),           // 9: chirp.common.ErrorCode
	(*chat.ChatMessage)(nil),        // 10: chirp.chat.ChatMessage
}
var file_proto_gateway_proto_depIdxs = []int32{
	0,  // 0: chirp.gateway.Packet.msg_id:type_name -> chirp.gateway.MsgID
	1,  // 1: chirp.gateway.PeerRegisterReq.supported_features:type_name -> chirp.gateway.PeerCapability
	9,  // 2: chirp.gateway.PeerRegisterResp.code:type_name -> chirp.common.ErrorCode
	1,  // 3: chirp.gateway.PeerRegisterResp.supported_features:type_name -> chirp.gateway.PeerCapability
	10, // 4: chirp.gateway.ChannelMessageNotify.message:type_name -> chirp.chat.ChatMessage
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_gateway_proto_init() }
func file_proto_gateway_proto_init() {
	if File_proto_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_gateway_proto_goTypes,
		DependencyIndexes: file_proto_gateway_proto_depIdxs,
		EnumInfos:         file_proto_gateway_proto_enumTypes,
		MessageInfos:      file_proto_gateway_proto_msgTypes,
	}.Build()
	File_proto_gateway_proto = out.File
	file_proto_gateway_proto_goTypes = nil
	file_proto_gateway_proto_depIdxs = nil
}
